"""Platform capability map: (group, capability, coveredBy, status, home, note)."""

R = lambda g, c, cov, st, home, note: {'group': g, 'capability': c, 'coveredBy': cov, 'status': st, 'home': home, 'note': note}

CAPMAP = [
 # Runtime & shell
 R('Runtime & shell', 'Web, desktop and mobile shells from one bundle', ['PAP-13','PAP-19','PAP-20','PAP-255','PAP-256','PAP-257','PAP-258','PAP-259','PAP-260'], 'covered', 'app-shell', 'Tauri 2 targets, installers, updater, native shim.'),
 R('Runtime & shell', 'Multi-monitor window manager and pop-out', ['PAP-21','PAP-262','PAP-263'], 'covered', 'app-shell', ''),
 R('Runtime & shell', 'PWA and offline app shell', ['PAP-18','PAP-11'], 'covered', 'app-shell', 'Data offline is realtime (PAP-148).'),
 R('Runtime & shell', 'Kiosk, TV and parallel-browser modes', ['PAP-23','PAP-158'], 'covered', 'app-shell', 'POS and check-in kiosks (commerce, engagement) reuse PAP-23.'),
 R('Runtime & shell', 'i18n and l10n (catalogs, RTL, Intl helpers, spec copy)', ['PAP-27','PAP-375','PAP-126'], 'covered', 'app-shell', 'Tenant-authored content translation is out of PAP-27; v0.3 with the translate skill.'),
 R('Runtime & shell', 'Time zones and recurrence (RRULE) engine', ['PAP-27','PAP-58','PAP-344'], 'gap', 'data-layer', 'Five modules need recurrence; none owns it. Cross suggestion r4/data-layer/recurrence-engine.'),
 R('Runtime & shell', 'Feature flags with kill switches and per-tenant rules', ['PAP-366','PAP-435'], 'covered', 'app-shell', ''),
 R('Runtime & shell', 'Client error handling and crash reporting', ['PAP-368'], 'covered', 'app-shell', ''),
 R('Runtime & shell', 'Custom domains and white-label branding', ['PAP-431','PAP-75','PAP-178'], 'covered', 'app-shell', 'White-label sending domains per tenant live in PAP-370 DKIM setup (partial, noted).'),
 R('Runtime & shell', 'Code signing, notarisation and auto-update', ['PAP-369','PAP-257'], 'covered', 'app-shell', ''),
 R('Runtime & shell', 'Native mobile capabilities (camera, biometrics, share, push)', ['PAP-260','PAP-381'], 'covered', 'app-shell', ''),
 R('Runtime & shell', 'Command palette, keyboard and keymaps', ['PAP-151','PAP-153','PAP-289','PAP-290','PAP-291'], 'covered', 'input', ''),
 R('Runtime & shell', 'Multi-input: touch, pen, gamepad, voice', ['PAP-150','PAP-154','PAP-157','PAP-158','PAP-159'], 'covered', 'input', ''),
 R('Runtime & shell', 'Settings registry (module-declared settings pages per scope)', ['PAP-63','PAP-447'], 'partial', 'app-shell', 'Slot exists; no registry, storage or generated pages. Cross suggestion r4/app-shell/settings-registry.'),
 R('Runtime & shell', 'Template upgrade for generated apps', ['PAP-430'], 'covered', 'app-shell', ''),
 # Data
 R('Data', 'Postgres, Drizzle schema-as-code, RLS multi-tenancy', ['PAP-30','PAP-32','PAP-33','PAP-34'], 'covered', 'data-layer', ''),
 R('Data', 'Local-first sync and offline write queue', ['PAP-36','PAP-270','PAP-271','PAP-272','PAP-148'], 'covered', 'data-layer', ''),
 R('Data', 'Typed API, OpenAPI and typed client', ['PAP-35','PAP-267','PAP-268','PAP-269'], 'covered', 'data-layer', ''),
 R('Data', 'Background jobs, cron, DLQ and staff jobs view', ['PAP-43','PAP-295'], 'covered', 'data-layer', ''),
 R('Data', 'Full-text and semantic search with a registry', ['PAP-39','PAP-138','PAP-296'], 'covered', 'data-layer', 'Unified search UI in collab (PAP-138).'),
 R('Data', 'File and media storage with variants', ['PAP-37'], 'covered', 'data-layer', ''),
 R('Data', 'Malware scanning, document previews, video thumbnails, text extraction', ['PAP-37'], 'gap', 'data-layer', 'Explicitly out of PAP-37. Cross suggestion r4/data-layer/file-scanning-previews.'),
 R('Data', 'CDN and edge caching', ['PAP-37','PAP-87'], 'gap', 'data-layer', 'Cross suggestion r4/data-layer/cdn-edge-cache (deferred).'),
 R('Data', 'Append-only audit log and record activity timeline', ['PAP-38','PAP-333'], 'covered', 'data-layer', ''),
 R('Data', 'Field encryption and secrets handling', ['PAP-353','PAP-300','PAP-444','PAP-17'], 'covered', 'data-layer', ''),
 R('Data', 'Backups, PITR and platform DR drill', ['PAP-30','PAP-354','PAP-274','PAP-53'], 'covered', 'data-layer', ''),
 R('Data', 'Export, data portability and round-trip import', ['PAP-205','PAP-420','PAP-421','PAP-422'], 'covered', 'migration', ''),
 R('Data', 'Tenant lifecycle, deletion, retention and PII classification', ['PAP-432','PAP-355'], 'covered', 'data-layer', ''),
 R('Data', 'Request idempotency and rate limiting', ['PAP-304'], 'covered', 'data-layer', ''),
 R('Data', 'Domain event bus, outbox and schema registry', ['PAP-303','PAP-436'], 'covered', 'data-layer', ''),
 R('Data', 'Data dictionary and observability (OTel, Grafana)', ['PAP-41','PAP-40'], 'covered', 'data-layer', ''),
 R('Data', 'Custom datasets and schema editor in-app', ['PAP-332'], 'covered', 'tables', ''),
 R('Data', 'Multi-region and data residency', ['PAP-56'], 'gap', 'platform-ops', 'Only mentioned in the auth ADR. New project issue r4/platform-ops/data-residency (deferred).'),
 R('Data', 'Multi-currency FX rates and revaluation', ['PAP-302','PAP-179'], 'gap', 'business-core', '`Money` carries a currency; nothing converts. Cross suggestion r4/business-core/fx-rates.'),
 # Identity
 R('Identity', 'Authentication: passkeys, magic links, OAuth, Tauri sessions', ['PAP-57','PAP-223','PAP-224','PAP-225'], 'covered', 'identity', ''),
 R('Identity', 'Organisations, workspaces, invitations, tenant switching', ['PAP-58'], 'covered', 'identity', ''),
 R('Identity', 'Permission engine, audiences, attribute policies, matrix tests', ['PAP-55','PAP-59','PAP-64','PAP-227','PAP-228','PAP-229'], 'covered', 'identity', ''),
 R('Identity', 'Agents as first-class principals', ['PAP-60'], 'covered', 'identity', ''),
 R('Identity', 'Staff impersonation with audit', ['PAP-61'], 'covered', 'identity', ''),
 R('Identity', 'SSO (SAML/OIDC) and SCIM', ['PAP-65','PAP-230','PAP-231','PAP-232'], 'covered', 'identity', ''),
 R('Identity', 'Session and device management, MFA, recovery', ['PAP-220','PAP-301'], 'covered', 'identity', ''),
 R('Identity', 'Customer API keys, outbound webhooks, SDK', ['PAP-222'], 'covered', 'identity', 'Deferred to v0.2 but fully specified.'),
 R('Identity', 'Tenant-installable OAuth apps (OIDC provider for third parties)', ['PAP-226','PAP-222'], 'gap', 'identity', 'PAP-226 serves Forgejo only. Cross suggestion r4/identity/oauth-provider-apps (deferred).'),
 R('Identity', 'Privacy: DSAR export and erasure, consent, legal pages', ['PAP-221','PAP-187'], 'covered', 'identity', 'Deferred; consent centre folded into PAP-187 WP0.'),
 R('Identity', 'Abuse, signup fraud and sending reputation controls', ['PAP-304','PAP-193','PAP-405','PAP-408'], 'partial', 'platform-ops', 'Rate limits and per-feature spam checks only. New project issue r4/platform-ops/abuse-controls.'),
 R('Identity', 'Sandbox or test-mode tenants for customers', ['PAP-240','PAP-363'], 'gap', 'identity', 'Test seeds exist for QA; no customer-facing sandbox tenant. Note for v0.3; no spec this round.'),
 # Collaboration
 R('Collaboration', 'Comments anchored to any entity with mentions and resolve', ['PAP-131','PAP-317','PAP-318','PAP-319'], 'covered', 'collab', ''),
 R('Collaboration', 'Presence, cursors, follow mode, agents as participants', ['PAP-141','PAP-146','PAP-149'], 'covered', 'realtime', ''),
 R('Collaboration', 'Notifications hub: in-app, email, Slack, digests, quiet hours', ['PAP-136','PAP-323','PAP-324','PAP-325'], 'covered', 'collab', ''),
 R('Collaboration', 'SMS and WhatsApp as notification channels', ['PAP-136','PAP-404'], 'gap', 'collab', 'Twilio exists for outreach only. Cross suggestion r4/collab/sms-notification-channel.'),
 R('Collaboration', 'Push transport (live events, Web Push, mobile push)', ['PAP-381'], 'covered', 'realtime', ''),
 R('Collaboration', 'Docs engine (repo MDX) and tenant-authored docs', ['PAP-128','PAP-379'], 'covered', 'collab', ''),
 R('Collaboration', 'Canvas UX-flow view generated from specs', ['PAP-132','PAP-123','PAP-320','PAP-321','PAP-322'], 'covered', 'collab', ''),
 R('Collaboration', 'Prompt and response logs with browser and replay', ['PAP-107','PAP-129','PAP-135'], 'covered', 'collab', ''),
 R('Collaboration', 'Changelogs per app and per tenant', ['PAP-133','PAP-52'], 'covered', 'collab', ''),
 R('Collaboration', 'Collaborative rich text editor', ['PAP-142'], 'covered', 'realtime', ''),
 R('Collaboration', 'Transactional email package', ['PAP-370'], 'covered', 'data-layer', ''),
 R('Collaboration', 'Screenshot and video annotation to issues', ['PAP-137'], 'covered', 'collab', ''),
 R('Collaboration', 'Rules and skills as browsable objects; ADR log', ['PAP-134','PAP-130'], 'covered', 'collab', ''),
 R('Collaboration', 'Contextual help panel and first-visit tours', ['PAP-380'], 'covered', 'collab', ''),
 R('Collaboration', 'Public help center and knowledge base per tenant', ['PAP-379','PAP-380'], 'partial', 'engagement', 'Tenant docs exist; no public site, categories, search page or feedback. New project issue r4/engagement/help-center.'),
 R('Collaboration', 'Staff to customer support inbox (email, in-app chat)', ['PAP-197','PAP-410','PAP-411','PAP-412'], 'covered', 'growth', 'Deferred to v0.2 but fully specified.'),
 R('Collaboration', 'Two-way conversational SMS and WhatsApp messaging', ['PAP-404','PAP-410'], 'gap', 'engagement', 'Outbound sequences only. New project issue r4/engagement/messaging-channels.'),
 R('Collaboration', 'Video calls and meetings', [], 'gap', 'engagement', 'Out of scope for v0.2; link fields to Zoom/Meet only. No spec this round.'),
 # Product surfaces
 R('Product surfaces', 'Tables and views engine with Airtable, Notion, ClickUp parity', ['PAP-161','PAP-162','PAP-163','PAP-164','PAP-165','PAP-166','PAP-167','PAP-168','PAP-169','PAP-170','PAP-172'], 'covered', 'tables', ''),
 R('Product surfaces', 'Dashboards with cross-filters and print route', ['PAP-173','PAP-385','PAP-386','PAP-387'], 'covered', 'tables', ''),
 R('Product surfaces', 'Formula engine', ['PAP-171','PAP-382','PAP-383','PAP-384'], 'covered', 'tables', ''),
 R('Product surfaces', 'Table automations (triggers, conditions, actions)', ['PAP-174','PAP-388','PAP-389','PAP-390'], 'covered', 'tables', ''),
 R('Product surfaces', 'Cross-module workflow engine with human tasks, waits and versions', ['PAP-174','PAP-388'], 'partial', 'workflows', 'Automations are single-table and stateless. New project workflows.'),
 R('Product surfaces', 'Generic approvals framework and task inbox', ['PAP-94','PAP-401','PAP-408','PAP-185','PAP-400'], 'partial', 'workflows', 'Five bespoke approval steps. New project issues r4/workflows/approvals-framework, task-inbox.'),
 R('Product surfaces', 'Forms builder: multi-page, logic, payments, public embeds, anti-spam', ['PAP-169','PAP-193'], 'partial', 'workflows', 'Single-page record-entry view and a Webflow embed. New project issues r4/workflows/forms-schema-runtime, r4/workflows/forms-publishing.'),
 R('Product surfaces', 'Document templates and generation (PDF, DOCX) beyond invoices', ['PAP-180','PAP-235','PAP-396'], 'partial', 'workflows', 'Invoices only. New project issues r4/workflows/document-templates, r4/workflows/document-generation.'),
 R('Product surfaces', 'E-signature with audit certificate', ['PAP-352'], 'gap', 'workflows', 'Only a Documenso mention in the OSS spike. New project issues r4/workflows/esign-core, r4/workflows/esign-audit-compliance.'),
 R('Product surfaces', 'Record detail page, activity, attachments, field history', ['PAP-333','PAP-334'], 'covered', 'tables', ''),
 R('Product surfaces', 'Spec builder, codegen, conformance tests, spec editor', ['PAP-114','PAP-115','PAP-120','PAP-122','PAP-124','PAP-362'], 'covered', 'spec-builder', ''),
 R('Product surfaces', 'Design system, theming, print and email kit', ['PAP-66','PAP-67','PAP-75','PAP-235'], 'covered', 'design-system', ''),
 R('Product surfaces', 'Labels, barcodes, QR codes and scanner input', ['PAP-235','PAP-260'], 'gap', 'design-system', 'Cross suggestion r4/design-system/labels-barcodes-qr.'),
 R('Product surfaces', 'Customer portal and staff console shells', ['PAP-62','PAP-63','PAP-363'], 'covered', 'identity', ''),
 R('Product surfaces', 'First-run onboarding wizard and template gallery', ['PAP-367','PAP-428'], 'covered', 'app-shell', ''),
 R('Product surfaces', 'In-app AI assistant over tenant data with citations and actions', ['PAP-291','PAP-39','PAP-380'], 'gap', 'assistant', 'Agents build the product; nothing lets tenants or customers talk to it. New project assistant.'),
 R('Product surfaces', 'Natural language to filters, formulas and views', ['PAP-279','PAP-382'], 'gap', 'assistant', 'New project issue r4/assistant/nl-to-views.'),
 R('Product surfaces', 'Customer-facing business characters (tenant-configurable agents)', ['PAP-103','PAP-113'], 'gap', 'assistant', 'Character schema is platform-scoped. New project issue r4/assistant/business-characters.'),
 R('Product surfaces', 'Unified search UI from the command palette', ['PAP-138','PAP-290'], 'covered', 'collab', ''),
 R('Product surfaces', 'Maps: geocoding, address field, distance filters', ['PAP-170','PAP-293','PAP-260'], 'partial', 'tables', 'Map view plots existing coordinates only. Cross suggestion r4/tables/address-geo-field.'),
 R('Product surfaces', 'Scheduled delivery of views and dashboards', ['PAP-387','PAP-421'], 'gap', 'tables', 'Cross suggestion r4/tables/scheduled-view-delivery.'),
 R('Product surfaces', 'Offline conflict and stale-data UX', ['PAP-144','PAP-148','PAP-327'], 'covered', 'realtime', ''),
 R('Product surfaces', 'In-app announcements and product messaging', ['PAP-133','PAP-323'], 'partial', 'engagement', 'Changelog feed exists; no targeted banners or modals. New project issue r4/engagement/announcements.'),
 R('Product surfaces', 'Feedback and feature request board', [], 'gap', 'engagement', 'New project issue r4/engagement/feedback-board.'),
 # Business operations
 R('Business operations', 'Platform billing: Stripe Billing, entitlements, metering', ['PAP-177','PAP-178','PAP-391'], 'covered', 'business-core', ''),
 R('Business operations', 'Double-entry ledger, period close, finance reports', ['PAP-179','PAP-392','PAP-393','PAP-394','PAP-183'], 'covered', 'business-core', ''),
 R('Business operations', 'Invoices, quotes, receipts, recurring and dunning', ['PAP-180','PAP-395','PAP-396','PAP-397'], 'covered', 'business-core', ''),
 R('Business operations', 'Connect payments and payouts, tax, PCI posture', ['PAP-181','PAP-182','PAP-359'], 'covered', 'business-core', ''),
 R('Business operations', 'Payroll adapter and runs', ['PAP-184','PAP-398','PAP-399','PAP-400'], 'covered', 'business-core', ''),
 R('Business operations', 'Expenses with receipt OCR; cash-flow dashboard', ['PAP-185','PAP-186'], 'covered', 'business-core', ''),
 R('Business operations', 'Bank feeds and reconciliation', ['PAP-186','PAP-424'], 'gap', 'business-core', 'Cross suggestion r4/business-core/bank-feeds-reconciliation (deferred).'),
 R('Business operations', 'Purchase orders, receiving, vendor bills, AP', ['PAP-183','PAP-175'], 'partial', 'commerce', 'AP aging report without AP documents. New project issue r4/commerce/purchasing-ap.'),
 R('Business operations', 'Budgeting and forecasting', ['PAP-183'], 'gap', 'business-core', 'Explicitly out of PAP-183; v0.3 note, no spec this round.'),
 R('Business operations', 'Products, variants, price lists and inventory', ['PAP-177','PAP-207'], 'gap', 'commerce', 'New project issue r4/commerce/catalog-inventory.'),
 R('Business operations', 'Orders, fulfilment, returns and refunds', [], 'gap', 'commerce', 'New project issue r4/commerce/orders-fulfilment.'),
 R('Business operations', 'POS mode with Stripe Terminal and offline sales', ['PAP-23','PAP-148'], 'gap', 'commerce', 'New project issue r4/commerce/pos-mode.'),
 R('Business operations', 'Tenant-to-customer subscriptions and recurring plans', ['PAP-177','PAP-181'], 'partial', 'commerce', 'PAP-177 bills the tenant; Connect accepts one-off payments. New project issue r4/commerce/customer-subscriptions.'),
 R('Business operations', 'Quotes, estimates and contracts', ['PAP-180','PAP-395'], 'partial', 'workflows', 'Quotes exist; contracts need templates and e-sign (workflows).'),
 R('Business operations', 'Projects, time tracking, time and materials billing', ['PAP-100','PAP-427'], 'gap', 'commerce', 'Agency pack has no time entries. New project issue r4/commerce/projects-time-billing.'),
 R('Business operations', 'HR core: directory, time-off, shifts, timesheets', ['PAP-399','PAP-400'], 'partial', 'commerce', 'Employees exist for payroll only. New project issue r4/commerce/hr-core.'),
 R('Business operations', 'Recruiting and ATS', [], 'gap', 'commerce', 'v0.3 note; a pack can compose forms and pipelines meanwhile. No spec this round.'),
 R('Business operations', 'Assets, maintenance and work orders (field service)', [], 'gap', 'commerce', 'New project issue r4/commerce/assets-work-orders.'),
 R('Business operations', 'Two-sided marketplace (vendors, split payments, payouts)', ['PAP-181','PAP-408'], 'gap', 'commerce', 'New project issue r4/commerce/marketplace-model.'),
 R('Business operations', 'Appointments, resource scheduling and booking pages', ['PAP-344','PAP-352','PAP-215'], 'gap', 'engagement', 'Cal.com spiked, nothing built. New project issues r4/engagement/scheduling-model, booking-engine, booking-pages.'),
 R('Business operations', 'Calendar sync (Google, Microsoft, ICS)', [], 'gap', 'engagement', 'New project issue r4/engagement/calendar-sync.'),
 R('Business operations', 'Memberships, check-in and attendance', ['PAP-177','PAP-23'], 'gap', 'engagement', 'New project issue r4/engagement/memberships-checkin.'),
 R('Business operations', 'Loyalty points and gift cards', ['PAP-179','PAP-407'], 'gap', 'engagement', 'New project issue r4/engagement/loyalty-gift-cards.'),
 R('Business operations', 'Surveys, NPS, CSAT and review requests', ['PAP-352'], 'gap', 'engagement', 'Formbricks spiked. New project issues r4/engagement/surveys-nps, reviews-requests.'),
 R('Business operations', 'LMS, courses and staff training', [], 'gap', 'engagement', 'v0.3: compose docs, forms, memberships. No spec this round.'),
 R('Business operations', 'Support ticketing', ['PAP-197','PAP-410','PAP-411','PAP-412'], 'covered', 'growth', 'Deferred v0.2.'),
 # Growth
 R('Growth', 'CRM entities, pipeline and contact views', ['PAP-187','PAP-189'], 'covered', 'growth', ''),
 R('Growth', 'Social scheduling with approval queue', ['PAP-190','PAP-401','PAP-402','PAP-403'], 'covered', 'growth', ''),
 R('Growth', 'Outreach sequences (email, SMS) with compliance', ['PAP-191','PAP-404','PAP-405','PAP-406'], 'covered', 'growth', ''),
 R('Growth', 'Bulk email campaigns and newsletters', ['PAP-191','PAP-351'], 'partial', 'growth', 'Sequences are drip, not broadcast. Cross suggestion r4/growth/bulk-campaigns.'),
 R('Growth', 'Landing pages and form capture (Webflow)', ['PAP-193'], 'covered', 'growth', 'Forms builder (workflows) supersedes the embed.'),
 R('Growth', 'Acquisition attribution analytics', ['PAP-194'], 'covered', 'growth', ''),
 R('Growth', 'Segments from CRM and usage', ['PAP-195'], 'covered', 'growth', ''),
 R('Growth', 'Referral and affiliate program', ['PAP-196','PAP-407','PAP-408','PAP-409'], 'covered', 'growth', ''),
 R('Growth', 'Content agent drafting for approval', ['PAP-192'], 'covered', 'growth', ''),
 R('Growth', 'SEO, CMS and blog', ['PAP-193'], 'gap', 'growth', 'Marketing site stays on Webflow by decision; help center and trust center cover SEO for owned pages. No spec this round.'),
 # Operations / ops
 R('Operations', 'Hosting, Coolify, deploy pipeline, previews', ['PAP-25','PAP-26','PAP-15'], 'covered', 'app-shell', ''),
 R('Operations', 'Public status page and incident communications', ['PAP-40','PAP-356'], 'gap', 'platform-ops', 'Alerts are internal only. New project issue r4/platform-ops/status-page.'),
 R('Operations', 'Security telemetry and alerting', ['PAP-356'], 'covered', 'quality', ''),
 R('Operations', 'Performance budgets (web and API)', ['PAP-87','PAP-242'], 'covered', 'quality', ''),
 R('Operations', 'Product analytics: events, funnels, retention, adoption', ['PAP-194','PAP-40','PAP-291'], 'partial', 'platform-ops', 'Acquisition and traces only. New project issue r4/platform-ops/product-analytics.'),
 R('Operations', 'Session replay with PII masking', [], 'gap', 'platform-ops', 'New project issue r4/platform-ops/session-replay.'),
 R('Operations', 'Experiments and A/B readouts', ['PAP-366'], 'partial', 'platform-ops', 'Variant flags without assignment or metrics. New project issue r4/platform-ops/experiments.'),
 R('Operations', 'Platform super-admin console (tenants, overrides, flags, DLQ)', ['PAP-63','PAP-43','PAP-366','PAP-61'], 'partial', 'platform-ops', 'Pieces exist per module; no platform surface. New project issue r4/platform-ops/superadmin-console.'),
 R('Operations', 'Tenant health scores and ops dashboards', ['PAP-391','PAP-432'], 'gap', 'platform-ops', 'New project issue r4/platform-ops/tenant-health-scores.'),
 R('Operations', 'Usage metering and credit spend reporting', ['PAP-391','PAP-98'], 'covered', 'business-core', ''),
 R('Operations', 'Supply-chain and CI security', ['PAP-358','PAP-80','PAP-357'], 'covered', 'forge', ''),
 R('Operations', 'Non-Linux CI capacity and flaky-test quarantine', ['PAP-371','PAP-90'], 'covered', 'forge', ''),
 # Developer experience
 R('Developer experience', 'Spec-first pages, codegen and golden path CLI', ['PAP-114','PAP-120','PAP-364','PAP-365','PAP-429'], 'covered', 'spec-builder', ''),
 R('Developer experience', 'Module system, contracts, conformance, swap tooling', ['PAP-433','PAP-434','PAP-435','PAP-441','PAP-442','PAP-446'], 'covered', 'module-system', 'Every new project ships the module trio.'),
 R('Developer experience', 'Storybook, docs engine, module docs generator', ['PAP-69','PAP-128','PAP-445'], 'covered', 'design-system', ''),
 R('Developer experience', 'Public API, SDK and webhooks for customers', ['PAP-222','PAP-269'], 'covered', 'identity', 'Deferred v0.2.'),
 R('Developer experience', 'Plugin and extension marketplace', ['PAP-28','PAP-433'], 'gap', 'module-system', 'Explicit non-goal of the module system for v0.2; tenant-installable extensions via manifests and OAuth apps are the v0.3 path.'),
 R('Developer experience', 'Test-mode seeds, fixtures and demo tenants', ['PAP-240','PAP-363'], 'covered', 'quality', ''),
 R('Developer experience', 'Library evaluation, registry, license policy, Renovate', ['PAP-209','PAP-211','PAP-216','PAP-217'], 'covered', 'libraries', ''),
 # Agent org
 R('Agent org', 'Roster, characters, sub-characters, prompts', ['PAP-103','PAP-104','PAP-284','PAP-285','PAP-286','PAP-287'], 'covered', 'agents', ''),
 R('Agent org', 'Skills, MCP allowlists, deny list, injection defences', ['PAP-105','PAP-106','PAP-298','PAP-299','PAP-210'], 'covered', 'agents', ''),
 R('Agent org', 'Budgets, kill switch, observability, sandbox', ['PAP-111','PAP-288','PAP-280','PAP-300'], 'covered', 'agents', ''),
 R('Agent org', 'Evals harness and golden tasks', ['PAP-110','PAP-308','PAP-309','PAP-310'], 'covered', 'agents', ''),
 R('Agent org', 'Handoff protocol, inbound triage, weekly re-audit', ['PAP-108','PAP-307','PAP-306'], 'covered', 'pm-linear', ''),
 R('Agent org', 'Agent org chart and memory', ['PAP-113','PAP-109'], 'covered', 'agents', ''),
 R('Agent org', 'Agent execution of commands with telemetry', ['PAP-291'], 'covered', 'input', ''),
 R('Agent org', 'Assistant safety evals and red-team', ['PAP-299','PAP-308'], 'gap', 'assistant', 'New project issue r4/assistant/safety-evals-redteam.'),
 # Compliance
 R('Compliance', 'Threat model and security baseline', ['PAP-219'], 'covered', 'identity', ''),
 R('Compliance', 'PCI SAQ-A posture', ['PAP-359'], 'covered', 'business-core', ''),
 R('Compliance', 'SOC 2, GDPR, HIPAA control mapping and evidence', ['PAP-219','PAP-355','PAP-354','PAP-356','PAP-38'], 'gap', 'platform-ops', 'Controls exist, mapping does not. New project issues r4/platform-ops/compliance-controls, evidence-automation.'),
 R('Compliance', 'Compliance profiles per tenant (HIPAA mode, student privacy)', ['PAP-126','PAP-355'], 'gap', 'platform-ops', 'PAP-126 hints at a compliance profile; nothing enforces. New project issue r4/platform-ops/compliance-profiles.'),
 R('Compliance', 'Accessibility program, statement and VPAT', ['PAP-73','PAP-156','PAP-160'], 'covered', 'input', ''),
 R('Compliance', 'Trust center, subprocessors, DPA and BAA', ['PAP-221'], 'gap', 'platform-ops', 'New project issue r4/platform-ops/trust-center.'),
 R('Compliance', 'Cookie consent and legal pages', ['PAP-221','PAP-194'], 'covered', 'identity', 'Deferred v0.2.'),
 R('Compliance', 'Data retention and hard purge', ['PAP-355','PAP-432'], 'covered', 'data-layer', ''),
 R('Compliance', 'License policy in CI', ['PAP-211'], 'covered', 'libraries', ''),
 R('Compliance', 'E-signature legal disclosures and certificates', [], 'gap', 'workflows', 'New project issue r4/workflows/esign-audit-compliance.'),
 # Verticals
 R('Verticals', 'Business profile and terminology map', ['PAP-126'], 'covered', 'spec-builder', ''),
 R('Verticals', 'Pack format, applier, gallery and five packs', ['PAP-207','PAP-426','PAP-427','PAP-428'], 'covered', 'migration', 'Deferred v0.2.'),
 R('Verticals', 'Packs wave 2: salon, gym, law, real estate', ['PAP-427'], 'gap', 'commerce', 'New project issue r4/commerce/vertical-packs-wave2.'),
 R('Verticals', 'Packs wave 3: ecommerce, nonprofit, school, church, construction, property, trades', ['PAP-427'], 'gap', 'commerce', 'New project issue r4/commerce/vertical-packs-wave3.'),
 R('Verticals', 'Pack conformance in CI', ['PAP-429'], 'gap', 'commerce', 'New project issue r4/commerce/pack-conformance-tests.'),
 R('Verticals', 'Migration agent and importers (Airtable, Notion, ClickUp, Stripe, QuickBooks)', ['PAP-208','PAP-199','PAP-202','PAP-203','PAP-204','PAP-206'], 'covered', 'migration', 'Shopify and Square importers for commerce are a v0.3 note.'),
]
