"""Gaps that belong in EXISTING projects (crossProjectSuggestions)."""

CROSS = [
 {
  'targetProject': 'data-layer', 'key': 'r4/data-layer/file-scanning-previews', 'title': 'Add file scanning and previews: ClamAV malware scan with quarantine states on the file entity, document previews (PDF first page, office via Gotenberg), video thumbnails and text extraction for search',
  'type': 'Build', 'tier': 'sonnet', 'effort': 'medium', 'size': 'M', 'priority': 3, 'surfaces': ['Customer', 'Staff'], 'milestone': 'Tenant-safe and observable', 'deferred': False,
  'blockedBy': ['PAP-37', 'PAP-43', 'PAP-296', 'PAP-39'], 'blocks': [],
  'goal': "Close the two items PAP-37 explicitly left out and every upload surface assumes: a malware scan on every completed upload with a quarantine state so nothing unscanned is served to another user, and previews (PDF and office first pages, video thumbnails) plus text extraction so attachments render in grids, record panels and support conversations and are searchable and groundable.",
  'scope_in': [
    "`packages/files/src/scan/`: ClamAV (`clamav/clamav` container in `ops/compose/files.yml`, measured against the PAP-296 6 GB budget; `clamd` streaming) as a PAP-43 job `files.scan` enqueued by `files.complete`; `file.scan_status pending|clean|infected|error` and `file.quarantined_at`; `files.getUrl` refuses non-`clean` files to anyone but the uploader with `FILE_QUARANTINED`",
    "`files.preview` job: PDF first page via `pdftoppm` (poppler), office documents via Gotenberg (LibreOffice container, optional behind a flag and the budget table), images reuse PAP-37 variants, video poster frame via `ffmpeg` at 2 s; stored as variants `preview-sm|md`; `<FilePreview/>` component in `@paperos/ui` with a graceful icon fallback",
    "`files.extractText` job for PDF, office and text types writing `file.text_excerpt` (first 20 KB) and a PAP-39 search registration `file` update so attachments are searchable and the assistant can ground on them",
    "Nightly reconcile: unscanned files older than 1 h re-enqueued; infected files reported as `security.file.infected` (PAP-356) and purged after 7 days",
  ],
  'scope_out': ['DLP or content classification', 'Virus scanning of repository artefacts (Trivy in PAP-80)'],
  'spec': [
    'Uploads are usable by the uploader immediately (optimistic) and by others only after `clean`; the UI shows a scanning badge (PAP-234 state)',
    'Scan and preview jobs run with `singletonKey = fileId`, time out at 60 s and 120 s, and never block the upload completion response',
    'Containers are optional per environment: without ClamAV the platform refuses to serve files to non-uploaders in production (fail closed) and warns in dev',
    'Text extraction respects `pii` rules: excerpts inherit the record\'s retention and are redacted from prompt logs',
  ],
  'provides': "`file.scan_status` and preview variants, jobs `files.scan|preview|extractText`, `<FilePreview/>`, compose additions, `security.file.infected` event",
  'consumes': "object storage and variants (PAP-37), jobs (PAP-43), resource budget (PAP-296), search registry (PAP-39), security telemetry (PAP-356), state components (PAP-234)",
  'consumed_by': "tables attachment field (PAP-339), record panel attachments (PAP-333), support inbox media (PAP-410), forms uploads, assistant grounding, engagement messaging media",
  'dod': ['EICAR test file is quarantined and reported; a PDF, a DOCX and an MP4 show previews in the attachment cell and record panel; extracted text is searchable; compose stack within budget (measured)'],
  'tests': {
    'Unit': 'status transitions; getUrl gating; excerpt truncation',
    'Integration': 'EICAR → infected → purge; preview jobs for each type with fixture files; reconcile re-enqueue',
  },
  'demo': "Upload a PDF and the EICAR file to a record; the PDF shows a preview thumbnail within seconds, the EICAR file shows quarantined and a security event appears in the Sentinel digest.",
  'edge': ['ClamAV signature update in progress: scans queue with retry and files stay pending; the reconcile job reports the backlog', 'Password-protected PDF: preview falls back to the icon and extraction records `encrypted`'],
  'deps': 'PAP-37, PAP-43 (hard), PAP-296 (hard: budget), PAP-39, PAP-356 (soft).',
  'builder': 'Forge', 'reviewer': 'Sentinel (Security Auditor)',
 },
 {
  'targetProject': 'data-layer', 'key': 'r4/data-layer/recurrence-engine', 'title': 'Build the shared recurrence engine: RRULE (RFC 5545) parsing and expansion with time zones, exceptions and bounds, used by jobs schedules, recurring invoices, calendar views, bookings and maintenance',
  'type': 'Build', 'tier': 'sonnet', 'effort': 'medium', 'size': 'S', 'priority': 2, 'surfaces': ['Developer'], 'milestone': 'Tenant-safe and observable', 'deferred': False,
  'blockedBy': ['PAP-302', 'PAP-27', 'PAP-43'], 'blocks': ['PAP-344'],
  'goal': "Stop five modules from each re-implementing \"every second Tuesday\": one `packages/core/recurrence` with an RFC 5545 `RRULE` model (rrule.js under the hood, wrapped in our types), time-zone-correct expansion across DST, exception dates and bounded iteration, a Zod schema for storing rules on any row, and a job helper that schedules the next occurrence.",
  'scope_in': [
    "`Recurrence` Zod schema (`rrule` string, `dtstart` with zone, `exdates[]`, `rdates[]`, `until|count`), `expand(rule, range, { zone, limit })`, `next(rule, after)`, `describe(rule, locale)` (human text via PAP-27 catalogs), `validate` (rejects unbounded rules without a range), and a Drizzle column helper `recurrence()`",
    "PAP-43 helper `scheduleRecurring(job, rule)` that enqueues the next occurrence with `singletonKey` and re-schedules after each run, replacing ad-hoc cron strings where a business rule is involved",
    "UI: `<RecurrenceEditor/>` in `@paperos/ui` (presets, custom builder, human preview) on the PAP-233 pickers",
  ],
  'scope_out': ['Calendar rendering (PAP-344 consumes)', 'iCalendar import/export beyond the RRULE string (engagement calendar sync)'],
  'spec': [
    'Expansion is deterministic and zone-aware: a 9:00 weekly rule in Europe/London stays 9:00 local across DST; tests cover forward and back transitions and non-existent local times',
    'Hard limit 10,000 occurrences per expansion call; callers page by range',
    '`describe` output is localised and used verbatim by calendar, booking and invoice UIs',
  ],
  'provides': "`packages/core/recurrence` (`Recurrence`, `expand`, `next`, `describe`, `recurrence()` column), `scheduleRecurring`, `<RecurrenceEditor/>`",
  'consumes': "contract-zero types (PAP-302), Intl and catalogs (PAP-27), jobs (PAP-43), pickers (PAP-233)",
  'consumed_by': "PAP-344 calendar (recurring events), PAP-180 WP4 recurring invoices, PAP-43 business schedules, engagement availability rules and maintenance schedules (commerce), workflows schedule triggers",
  'dod': ['Library merged with 100 percent branch coverage on expansion; editor in Storybook; PAP-344 and PAP-180 WP4 comment confirming adoption'],
  'tests': {
    'Unit': 'RFC 5545 examples suite; DST fixtures for London, New York, Sydney and Kathmandu; exdates; limits',
    'Property': 'fast-check: `next(rule, t)` equals the first element of `expand(rule, [t, ∞))` for random rules',
  },
  'demo': "Build \"first Monday of every month at 9:00 Sydney\" in the editor, read the human description, and print the next twelve occurrences across the April DST change.",
  'edge': ['Rule with `BYSETPOS` and `BYDAY` combinations rrule.js mishandles: covered by the RFC suite with documented deviations'],
  'deps': 'PAP-302, PAP-27 (hard), PAP-43, PAP-233 (soft).',
  'builder': 'Forge', 'reviewer': 'Sentinel (Edge Case Hunter)', 'tenant_data': False, 'module_edge': False,
 },
 {
  'targetProject': 'data-layer', 'key': 'r4/data-layer/cdn-edge-cache', 'title': 'Add CDN and edge caching for public assets, public views and embeds, and signed file downloads, with cache keys, purge on change and a provider decision (Caddy cache versus Bunny or Cloudflare)',
  'type': 'Infra', 'tier': 'sonnet', 'effort': 'medium', 'size': 'S', 'priority': 4, 'surfaces': ['Developer', 'Customer'], 'milestone': 'Tenant-safe and observable', 'deferred': True,
  'blockedBy': ['PAP-37', 'PAP-26', 'PAP-172', 'PAP-87', 'PAP-431'], 'blocks': [],
  'goal': "Make public pages fast everywhere and stop MinIO from serving the same image ten thousand times: an ADR choosing between Caddy's cache module on the VPS and a CDN in front (Bunny or Cloudflare) for static bundles, public view and form pages, help center and status pages, and signed file downloads, with cache keys that respect tenant hosts, purge hooks on publish and a per-PR budget check.",
  'scope_in': [
    "ADR with measurements from a PAP-87 Lighthouse run from three regions; chosen provider configured as code in `paperos-infra` (PAP-25) with custom-domain support matching PAP-431 (on-demand TLS must still work)",
    "Cache rules: immutable hashed bundles (1 year), public pages (60 s stale-while-revalidate), file variants (signed URLs with cache-friendly signatures scoped by tenant, 1 h), never for authenticated API responses; purge hook `cache.purge(paths)` called by publish events (views PAP-172, help center, status page)",
    "Observability: hit ratio and origin egress in PAP-40 dashboards",
  ],
  'scope_out': ['Edge compute', 'Image optimisation at the edge (variants exist in PAP-37)'],
  'spec': [
    'Signed download URLs include the variant and tenant in the path so the cache never serves one tenant\'s file under another host',
    'Purge is idempotent and asynchronous; publish flows do not wait on it',
    'Fallback: if the CDN is down, DNS failover to origin is documented in the runbook',
  ],
  'provides': "the ADR, provider config as code, cache rules, `cache.purge`, dashboards",
  'consumes': "files and variants (PAP-37), deploy pipeline (PAP-26), public tokens (PAP-172), performance budgets (PAP-87), custom domains (PAP-431), infra repo (PAP-25), observability (PAP-40)",
  'consumed_by': "app-shell static deploys, engagement help center and booking pages, workflows public forms, platform-ops status and trust pages",
  'dod': ['Public demo page LCP under 1.5 s from EU and US test locations; hit ratio dashboard live; purge proven on a view republish; custom domain still issues TLS'],
  'tests': {'Integration': 'cache headers per rule; purge; cross-tenant signed URL isolation', 'Perf': 'PAP-87 runs before and after'},
  'demo': "Load the demo public view from two regions before and after, show the LCP drop and the cache hit ratio, then republish the view and see the purge.",
  'edge': ['Tenant custom domain behind the CDN needs its own certificate path: documented per provider; the domain wizard (PAP-431) shows provider-specific CNAME instructions'],
  'deps': 'PAP-37, PAP-26, PAP-431 (hard), PAP-172, PAP-87, PAP-40 (soft).',
  'builder': 'Forge', 'reviewer': 'Sentinel (Code Reviewer)', 'tenant_data': False, 'module_edge': False,
 },
 {
  'targetProject': 'collab', 'key': 'r4/collab/sms-notification-channel', 'title': 'Add SMS and WhatsApp as notification channels on the notification core: Twilio provider shared with outreach, per-kind opt-in, consent and quiet hours, STOP handling and cost metering',
  'type': 'Build', 'tier': 'sonnet', 'effort': 'medium', 'size': 'S', 'priority': 4, 'surfaces': ['Customer', 'Staff'], 'milestone': 'Knowledge surfaced everywhere', 'deferred': True,
  'blockedBy': ['PAP-136', 'PAP-324', 'PAP-404', 'PAP-405', 'PAP-391'], 'blocks': [],
  'goal': "Let notifications reach phones: an `sms` (and `whatsapp`) channel in the PAP-136 notification core reusing the PAP-404 Twilio provider and the PAP-405 compliance rules, opt-in per kind in the preferences page (PAP-323), quiet hours (PAP-324), STOP handling shared with outreach, and cost metering, so booking reminders, approval requests and security alerts can be texted.",
  'scope_in': [
    "`NotificationChannel` `sms` and `whatsapp` adapters in `packages/collab/notifications/channels/`: render kind templates to 160-character variants with a short link (PAP-136 templates gain `sms` bodies), send via the PAP-404 provider client, delivery status back to `notification_delivery`",
    "Preferences: phone number verification (OTP via the same provider), per-kind channel toggles restricted to kinds flagged `smsEligible` (reminders, approvals, security alerts; never marketing), quiet hours apply; STOP marks the number suppressed for notifications and outreach alike",
    "Metering `outreach.messages` (PAP-391) with `channel: sms|whatsapp`; tenant daily caps",
  ],
  'scope_out': ['Two-way conversations (engagement messaging channels)', 'Bulk campaigns'],
  'spec': ['Transactional only: kinds must be flagged `smsEligible`; the flag is reviewed by Sentinel per kind', 'Numbers stored E.164, verified, encrypted at rest (PAP-353)', 'WhatsApp uses approved templates; falls back to SMS when no template applies'],
  'provides': "`sms` and `whatsapp` notification channels, phone verification, `smsEligible` kind flag, preference UI additions",
  'consumes': "notification core, inbox and digests (PAP-136, PAP-323, PAP-324), outreach provider and compliance (PAP-404, PAP-405), metering (PAP-391), encryption (PAP-353)",
  'consumed_by': "engagement booking reminders and surveys, workflows approvals and signature requests, platform-ops status subscribers, security alerts (PAP-356)",
  'dod': ['Verified phone receives a booking reminder fixture in the Twilio test sandbox; quiet hours defer; STOP suppresses both notifications and outreach; usage metered'],
  'tests': {'Unit': 'template shortening; eligibility; quiet hours', 'Integration': 'provider send and status webhook with recorded fixtures; STOP propagation'},
  'demo': "Verify a phone in preferences, enable SMS for approvals, submit an expense over threshold and receive the text with a signed approve link.",
  'edge': ['Number ported or invalid: provider error marks it unverified and falls back to email with a notice'],
  'deps': 'PAP-136, PAP-324 (hard), PAP-404, PAP-405 (hard: shared client and rules), PAP-391, PAP-353 (soft).',
  'builder': 'Beacon', 'reviewer': 'Sentinel (Security Auditor)',
 },
 {
  'targetProject': 'business-core', 'key': 'r4/business-core/fx-rates', 'title': 'Build the multi-currency FX rate service: daily rates from ECB and Open Exchange Rates adapters, convert(Money, currency, date), reporting currency, realised and unrealised gain posting rules and revaluation job',
  'type': 'Build', 'tier': 'opus', 'size': 'M', 'priority': 4, 'surfaces': ['Staff', 'Developer'], 'milestone': 'Ledger and reports', 'deferred': True,
  'blockedBy': ['PAP-302', 'PAP-179', 'PAP-394', 'PAP-183', 'PAP-43'], 'blocks': [],
  'goal': "Let a tenant invoice in EUR, pay a supplier in USD and report in GBP without spreadsheets: an `FxPort` with ECB (free, daily) and Open Exchange Rates adapters storing daily rates, `convert(money, to, date)` with documented rounding, a tenant reporting currency, posting rules for realised gains and losses on settlement and a month-end revaluation job for open balances, so PAP-183 reports read in one currency.",
  'scope_in': [
    "`fx_rate` (base, quote, date, rate, source) with a daily PAP-43 job and manual override rows (audited); `FxPort.convert(money, to, date)` using minor units and banker's rounding, `rateFor`, `describeConversion`; tenant `reportingCurrency` in finance settings (PAP-175)",
    "Posting rules (PAP-394): `fx.realised` on payment settlement when document and payment currencies differ; `fx.unrealised` revaluation entries for open receivables, payables and cash at month end with automatic reversal next period",
    "Reports (PAP-183) gain a currency parameter; document totals show original and reporting currency; approvals (workflows) use converted thresholds",
  ],
  'scope_out': ['Live intraday rates', 'Hedging'],
  'spec': ['Rates are immutable per (base, quote, date, source); corrections are new rows with `supersedes`', 'Every conversion stores the rate used on the posting so reports are reproducible', 'Missing rate for a date falls back to the previous business day and flags the entry'],
  'provides': "`FxPort` with two adapters, `fx_rate`, posting rules, revaluation job, reporting currency setting, `describeConversion`",
  'consumes': "`Money` (PAP-302), ledger and posting rules (PAP-179, PAP-394), reports (PAP-183), jobs (PAP-43), finance settings (PAP-175)",
  'consumed_by': "workflows approvals thresholds, commerce price lists and marketplace splits, PAP-183 reports, PAP-186 cash dashboard, engagement loyalty valuation",
  'dod': ['EUR invoice paid in USD posts a realised gain; month-end revaluation and reversal balance; P&L reads in GBP; rates job idempotent'],
  'tests': {'Unit': 'rounding and minor units; fallback; supersede', 'Integration': 'posting traces for realised and unrealised; report currency switch'},
  'demo': "Issue a EUR invoice on a GBP-reporting tenant, receive USD, and walk the ledger entries including the realised difference and the month-end revaluation.",
  'edge': ['Currency with zero decimals (JPY) and three decimals (KWD): minor unit handling tested explicitly'],
  'deps': 'PAP-302, PAP-179, PAP-394 (hard), PAP-183, PAP-43 (soft).',
  'builder': 'Ledger', 'reviewer': 'Sentinel (Code Reviewer)',
 },
 {
  'targetProject': 'business-core', 'key': 'r4/business-core/bank-feeds-reconciliation', 'title': 'Build bank feeds and reconciliation: BankFeedPort with Plaid and GoCardless adapters, statement import, matching rules to documents and ledger entries, reconciliation UI and Stripe payout reconciliation',
  'type': 'Build', 'tier': 'opus', 'size': 'L', 'priority': 4, 'surfaces': ['Staff'], 'milestone': 'Payroll adapter and cash dashboard', 'deferred': True,
  'blockedBy': ['PAP-179', 'PAP-394', 'PAP-180', 'PAP-181', 'PAP-353', 'PAP-200'], 'blocks': [],
  'goal': "Close the books against the bank: a `BankFeedPort` with Plaid (US) and GoCardless Bank Account Data (UK and EU) adapters plus CSV and OFX statement import (PAP-200 patterns), transaction matching rules to invoices, bills, payroll and Stripe payouts (with fee splits from PAP-181 balance transactions), a reconciliation screen with suggested matches and rules, and the cash accounts in PAP-186 marked reconciled.",
  'scope_in': [
    "`bank_account` (institution, encrypted tokens PAP-353, currency, ledger account), `bank_txn` (date, amount, description, counterparty, status unmatched|matched|excluded, match refs); adapters with webhook or polling sync; statement import via the migration import framework connectors (PAP-200 CSV, OFX parser)",
    "Matching: exact amount and reference, fuzzy counterparty, Stripe payout → sum of charges minus fees (PAP-181 balance transactions) creating fee postings; user-defined rules (counterparty contains → account); one-click create expense (PAP-185) or transfer",
    "Reconciliation UI `/finance/reconcile` on a grid with side-by-side suggestions, bulk accept, period close integration (PAP-393 lock refuses with unreconciled items unless overridden)",
  ],
  'scope_out': ['Payments initiation from the bank', 'Cash forecasting (PAP-186 shows reconciled cash)'],
  'spec': ['Feeds are read-only; tokens never leave the server; sync is incremental with cursors', 'A match posts nothing new unless creating an expense or transfer; it links; unlinking is audited', 'Duplicates across feed and statement import are detected by (account, date, amount, fingerprint)'],
  'provides': "`BankFeedPort` with adapters, tables, matching engine and rules, reconciliation UI, period close hook",
  'consumes': "ledger and posting rules (PAP-179, PAP-394), documents (PAP-180), Connect balance transactions (PAP-181), encryption (PAP-353), CSV import (PAP-200), expenses (PAP-185), period close (PAP-393)",
  'consumed_by': "PAP-186 cash dashboard (reconciled flag), PAP-183 reports, commerce purchasing (bill paid detection), platform-ops compliance evidence (reconciliation as a control)",
  'dod': ['Sandbox Plaid and GoCardless accounts sync; a Stripe payout reconciles to its charges and fees; 80 percent of fixture transactions auto-match; period close refuses with open items'],
  'tests': {'Unit': 'matching rules and scoring; duplicate detection; payout decomposition', 'Integration': 'recorded provider fixtures; statement import round trip'},
  'demo': "Connect the sandbox bank, watch last month's transactions arrive, accept the suggested matches including the Stripe payout with fees, and close the period.",
  'edge': ['Bank re-posts a transaction with a changed description: fingerprint match keeps the link and records the change'],
  'deps': 'PAP-179, PAP-394, PAP-180, PAP-181 (hard), PAP-353 (hard), PAP-200, PAP-185, PAP-393 (soft).',
  'builder': 'Ledger', 'reviewer': 'Sentinel (Security Auditor)',
 },
 {
  'targetProject': 'tables', 'key': 'r4/tables/scheduled-view-delivery', 'title': 'Add scheduled delivery of views and dashboards: PDF and CSV snapshots on a recurrence to email, Slack or a share link, rendered per recipient permissions, with run history',
  'type': 'Build', 'tier': 'sonnet', 'effort': 'medium', 'size': 'S', 'priority': 4, 'surfaces': ['Staff', 'Customer'], 'milestone': 'View sharing, formulas, dashboards', 'deferred': True,
  'blockedBy': ['PAP-387', 'PAP-172', 'PAP-235', 'PAP-136', 'PAP-325'], 'blocks': [],
  'goal': "Send the Monday report without anyone opening the app: schedule any saved view or dashboard for delivery as PDF (PAP-387 print route through PAP-235) or CSV on a recurrence (shared engine) to email recipients, a Slack channel (PAP-325) or a refreshed share link, rendering each recipient's copy under their own permissions, with a run history and failure notifications.",
  'scope_in': ["`view_schedule` (view or dashboard, recurrence, format, recipients as principals or emails, filters snapshot), job `views.deliver` rendering per recipient with `callAs` (PAP-268) so permission filtering applies, attachments under 10 MB else a share link (PAP-172 token), run history grid", "UI: `Schedule` action in the view menu and dashboard header with the `<RecurrenceEditor/>`; recipients picker restricted to principals who may see the view plus external emails only for public-shareable views"],
  'scope_out': ['Report builder (saved views are it)', 'Alerts on data thresholds (automations PAP-174 handle)'],
  'spec': ['Rendering runs as the recipient, never as the scheduler, so nobody receives rows they cannot see', 'External emails receive only views marked publicly shareable; the schedule refuses otherwise', 'Failures notify the owner (PAP-136) and pause after three consecutive errors'],
  'provides': "`view_schedule`, `views.deliver` job, schedule UI, run history",
  'consumes': "print route (PAP-387), sharing tokens (PAP-172), print kit (PAP-235), notifications and Slack (PAP-136, PAP-325), `callAs` (PAP-268), recurrence engine",
  'consumed_by': "business-core reports (weekly P&L), engagement (booking summaries), commerce (stock reports), platform-ops (health digests)",
  'dod': ['Weekly dashboard PDF arrives in Mailpit and Slack for two recipients with different permissions showing different rows; CSV variant; pause after failures'],
  'tests': {'Unit': 'recipient eligibility; size fallback', 'Integration': 'per-recipient rendering differs by permission; Slack post; pause logic'},
  'demo': "Schedule the cash dashboard every Monday 8:00 to Justin and the bookkeeper, run it now, and open the two PDFs side by side.",
  'edge': ['View deleted: schedule pauses with a notification rather than sending an error PDF'],
  'deps': 'PAP-387, PAP-172, PAP-235 (hard), PAP-136, PAP-325, PAP-268 (soft), `r4/data-layer/recurrence-engine` (hard).',
  'builder': 'Nova', 'reviewer': 'Sentinel (Code Reviewer)',
 },
 {
  'targetProject': 'tables', 'key': 'r4/tables/address-geo-field', 'title': 'Add an address and location field type with a geocoding provider port, autocomplete, map view binding and distance and within-area filter operators in the FilterTree',
  'type': 'Build', 'tier': 'sonnet', 'effort': 'medium', 'size': 'M', 'priority': 4, 'surfaces': ['Customer', 'Staff'], 'milestone': 'All view types', 'deferred': True,
  'blockedBy': ['PAP-338', 'PAP-170', 'PAP-279', 'PAP-293', 'PAP-260'], 'blocks': [],
  'goal': "Make places first-class: an `address` field type (structured components plus a point) with a `GeocodingPort` (Nominatim self-hosted or MapTiler, decided per PAP-293's map ADR) for autocomplete and forward and reverse geocoding, direct binding to the PAP-170 map view, `withinKm` and `inArea` operators in the shared filter grammar compiled to PostGIS, and current-location capture on mobile (PAP-260).",
  'scope_in': ["Field type `address` in the PAP-338 framework (`components`, `formatted`, `point geography(Point)`, `precision`, `provider ref`); PostGIS extension enabled in PAP-32 migrations; editor with autocomplete and a map pin adjust; cell renderer with a static map thumbnail (cached)", "`GeocodingPort` adapters `nominatim` (compose container behind the budget table) and `maptiler` (key via PAP-353), with a daily quota and caching by normalised query", "FilterTree ops `withinKm(point, km)` and `inArea(polygon)` in PAP-279 with SQL (PostGIS) and in-memory implementations; map view (PAP-170) gains radius and draw-area filters that emit these ops"],
  'scope_out': ['Routing and directions (commerce delivery uses external links in v0.2)', 'Territory management'],
  'spec': ['Geocoding is debounced and cached; provider quota exhaustion degrades to manual entry with a notice', 'Points are stored in WGS84; distance ops use geography for correctness', 'Import (PAP-349) maps address-like columns to the field and geocodes in a job with progress'],
  'provides': "`address` field type, `GeocodingPort` with two adapters, FilterTree geo ops, map view filters, import mapping",
  'consumes': "field framework (PAP-338), map view (PAP-170), filter grammar (PAP-279), map library ADR (PAP-293), geolocation plugin (PAP-260), encryption (PAP-353), import wizard (PAP-349)",
  'consumed_by': "growth CRM (contact and company addresses), commerce delivery and assets, engagement resources and booking locations, packs (real estate, property, trades)",
  'dod': ['Contacts get geocoded addresses; map view shows them; a `withinKm` filter returns the right rows in SQL and in-memory; mobile captures current location; quota degradation tested'],
  'tests': {'Unit': 'component normalisation; op compilation parity SQL vs memory', 'Integration': 'recorded geocoder fixtures; import geocoding job'},
  'demo': "Type an address into a new field with autocomplete, drop the pin, switch to the map view and draw a radius filter around the office.",
  'edge': ['Ambiguous address (multiple matches): editor shows candidates; nothing is stored until one is picked'],
  'deps': 'PAP-338, PAP-170, PAP-279 (hard), PAP-293 (hard: decision), PAP-260, PAP-353, PAP-349 (soft).',
  'builder': 'Nova', 'reviewer': 'Sentinel (Edge Case Hunter)',
 },
 {
  'targetProject': 'design-system', 'key': 'r4/design-system/labels-barcodes-qr', 'title': 'Add labels, barcodes and QR codes to the print kit: Barcode and QRCode components, label templates for Avery and thermal sizes, a barcode field type helper and scanner input handling',
  'type': 'Build', 'tier': 'sonnet', 'effort': 'medium', 'size': 'S', 'priority': 4, 'surfaces': ['Staff', 'Customer'], 'milestone': 'Themable per tenant with docs', 'deferred': True,
  'blockedBy': ['PAP-235', 'PAP-338', 'PAP-260', 'PAP-150'], 'blocks': [],
  'goal': "Let the product print and scan the physical world: `<Barcode/>` (Code 128, EAN-13, UPC-A via `bwip-js`) and `<QRCode/>` components in the PAP-235 print kit, label templates for common Avery sheets and 4×6 thermal labels with a print route, a `barcode` field type helper for the tables engine, and a scanner input handler that recognises keyboard-wedge scans and the PAP-260 native scanner through the PAP-150 input abstraction.",
  'scope_in': ["`packages/ui-print/src/{Barcode,QRCode,LabelSheet}.tsx` with SVG output, `labels.yaml` template registry (Avery 5160, 5163, 4×6 thermal, 2×1 shelf), `/print/labels` route taking a view query and a template", "`barcode` field type (PAP-338 framework) validating symbology check digits and rendering the barcode in cells and record panels", "`useScannerInput()` hook: detects wedge scans by inter-key timing and suffix, routes to the focused field or a `scan` command; native scanner via PAP-260 plugin"],
  'scope_out': ['Printer drivers (browser print and PDF only; ESC/POS is the POS issue)', 'Label design canvas'],
  'spec': ['Barcodes render as SVG so they scale in PDF and on screen; QR payloads are signed by the caller, never here', 'Label sheets align within 1 mm on the PDF (measured with a printed test sheet)', 'Scanner detection never swallows normal typing (timing threshold configurable)'],
  'provides': "`<Barcode/>`, `<QRCode/>`, `<LabelSheet/>`, label templates and print route, `barcode` field type, `useScannerInput()`",
  'consumes': "print kit (PAP-235), field framework (PAP-338), native scanner (PAP-260), input abstraction (PAP-150)",
  'consumed_by': "commerce catalog and POS, engagement member cards, workflows document QR verification links, migration (Airtable barcode field mapping PAP-415)",
  'dod': ['Print a sheet of 30 product labels aligned to Avery 5160 from a saved view; scan one back into a form with a wedge scanner simulation; QR verifies in a phone camera'],
  'tests': {'Unit': 'check digits; label geometry; wedge timing detection', 'E2E': 'print route PDF snapshot; scan into field'},
  'demo': "Open the products view, print shelf labels for the selection, then scan one with a phone into the inventory adjust form.",
  'edge': ['Right-to-left locale: label text flips, barcode does not (tested)'],
  'deps': 'PAP-235, PAP-338 (hard), PAP-260, PAP-150 (soft).',
  'builder': 'Iris', 'reviewer': 'Sentinel (Visual Inspector)', 'tenant_data': False, 'module_edge': False,
 },
 {
  'targetProject': 'app-shell', 'key': 'r4/app-shell/settings-registry', 'title': 'Build the settings registry: modules declare settings sections and schemas in their manifests, the shell generates tenant, workspace and user settings pages with permissions, audit and search',
  'type': 'Build', 'tier': 'sonnet', 'effort': 'high', 'size': 'M', 'priority': 2, 'surfaces': ['Staff', 'Customer', 'Developer'], 'milestone': 'Multi-monitor and PWA polish', 'deferred': False,
  'blockedBy': ['PAP-264', 'PAP-447', 'PAP-63', 'PAP-59', 'PAP-38', 'PAP-124'], 'blocks': ['PAP-266'],
  'goal': "Stop every module from hand-building its settings page: manifests declare `settings.sections[]` with a Zod schema, scope (tenant, workspace, user), permission and UI hints; the shell fills `shell.settings.sections` (PAP-447) with generated forms (PAP-124 form-from-schema patterns), stores values in `settings` tables per scope with RLS, audits changes (PAP-38), exposes `useSetting(key)` with live updates, and makes settings searchable from the command palette.",
  'scope_in': ["Manifest extension `settings: [{ id, scope, schema, permission, group, order, secret?: string[] }]` validated by PAP-433; tables `tenant_setting`, `workspace_setting`, `user_setting` (`module`, `key`, `value jsonb`, versioned); `settings.get|set` procedures with schema validation and permission checks; `useSetting`, `useSettings(module)` hooks with Electric live updates (PAP-326)", "Generated pages `/settings`, `/console/settings/:section`, `/portal/settings/:section` with the PAP-233 adapters, secret fields via the secrets port (PAP-444) never echoed, search registration (PAP-39) of section titles and field labels, deep links from the help panel", "Migration of existing hand-built settings (PAP-63's settings page, PAP-58 org settings, PAP-27 locale, PAP-75 branding) to registry declarations with an ADR"],
  'scope_out': ['Platform admin settings (platform-ops console)', 'Per-record settings'],
  'spec': ['Precedence user > workspace > tenant > manifest default, resolved server-side; a section may forbid lower-scope overrides', 'Every `set` writes an audit row with before and after (secrets redacted); a `settings.changed` event carries module and key', 'Schema changes are versioned with upcasters (PAP-436 pattern) so stored values migrate on read'],
  'provides': "settings manifest extension, tables and procedures, hooks, generated settings pages, search registration, `settings.changed` event",
  'consumes': "module manifests (PAP-264, PAP-433), settings slot (PAP-447), console and portal shells (PAP-63, PAP-62), permission engine (PAP-59), audit (PAP-38), form patterns (PAP-124, PAP-233), secrets port (PAP-444), live reads (PAP-326), search (PAP-39)",
  'consumed_by': "every module (assistant, engagement, commerce, workflows and platform-ops all declare settings), PAP-266 module toggles (as a section), PAP-367 onboarding (writes settings)",
  'dod': ['Three existing settings pages migrated to declarations with identical behaviour; a new module adds a section by manifest only; precedence and audit tested; search finds a setting from the palette'],
  'tests': {'Unit': 'precedence; schema validation; upcaster', 'E2E': 'edit at tenant then override at user; secret never echoed; deep link from help panel'},
  'demo': "Add a `bookingReminderHours` setting to the engagement manifest, reload, find it from the command palette, change it at tenant scope and see the audit row.",
  'edge': ['Module disabled: its sections hide but stored values persist for re-enable', 'Invalid stored value after a schema change without an upcaster: page shows the default with a repair notice'],
  'deps': 'PAP-264, PAP-447, PAP-433 (hard), PAP-63, PAP-59, PAP-38 (hard), PAP-124, PAP-233, PAP-444, PAP-326, PAP-39 (soft).',
  'builder': 'Forge', 'reviewer': 'Sentinel (Code Reviewer)',
 },
 {
  'targetProject': 'identity', 'key': 'r4/identity/oauth-provider-apps', 'title': 'Add tenant-installable OAuth apps: OIDC provider for third-party apps with consent screens, client registration, scopes mapped to API key scopes, token introspection and revocation',
  'type': 'Build', 'tier': 'opus', 'size': 'M', 'priority': 4, 'surfaces': ['Developer', 'Staff', 'Customer'], 'milestone': 'Agent principals and enterprise', 'deferred': True,
  'blockedBy': ['PAP-226', 'PAP-222', 'PAP-60', 'PAP-220', 'PAP-38'], 'blocks': [],
  'goal': "Let other software log in as a PaperOS user with permission: extend the PAP-226 OIDC provider (built for Forgejo SSO) into a tenant-facing OAuth 2.1 and OIDC authorization server where tenants register client apps, users see a consent screen listing scopes, scopes map to the PAP-222 API key scope model, tokens can be introspected and revoked, and every grant appears in session management (PAP-220).",
  'scope_in': ["Better Auth OIDC provider plugin configuration: `oauth_client` (tenant, name, redirect URIs, PKCE required, scopes allowed, logo, status), authorization code with PKCE only, refresh tokens with rotation, `introspect` and `revoke` endpoints, JWKS per tenant", "Consent screen page (spec) with scope descriptions from the PAP-222 scope registry; grants listed under `/portal/settings/security` and the console with revoke; developer page section in `/console/developers` for client registration", "Audit (PAP-38) of grants and revocations; rate limits on token endpoints (PAP-304)"],
  'scope_out': ['Dynamic client registration', 'Device flow', 'Acting as an OAuth client to third parties (PAP-57)'],
  'spec': ['Scopes never exceed the granting user\'s permissions; tokens carry the user principal and the client id; `can()` evaluates the user with a `via: client` attribute so policies may restrict clients', 'Refresh token reuse detection revokes the family', 'Client secrets hashed; public clients use PKCE only'],
  'provides': "OAuth 2.1 and OIDC authorization server for tenants, `oauth_client`, consent screen, grants management, introspection and revocation",
  'consumes': "OIDC provider base (PAP-226), API key scopes (PAP-222), agent principals model (PAP-60), sessions (PAP-220), audit (PAP-38), rate limits (PAP-304)",
  'consumed_by': "tenants' integrations, future marketplace extensions (module-system v0.3), assistant BYO tools (v0.3)",
  'dod': ['A sample third-party app completes login with consent, calls the API with a scoped token, is revoked from the portal and loses access; refresh reuse detection tested; conformance against an OIDC certification test subset'],
  'tests': {'Unit': 'scope intersection; PKCE; rotation', 'Integration': 'full code flow with recorded client; introspection; revocation propagation'},
  'demo': "Register \"Zapier-like app\" in the developer page, log in from the sample app, approve two scopes, list the grant in the portal and revoke it.",
  'edge': ['User removed from the tenant: all grants for that tenant revoke immediately'],
  'deps': 'PAP-226, PAP-222 (hard), PAP-60, PAP-220, PAP-38 (hard), PAP-304 (soft).',
  'builder': 'Forge', 'reviewer': 'Sentinel (Security Auditor)',
 },
 {
  'targetProject': 'growth', 'key': 'r4/growth/bulk-campaigns', 'title': 'Build bulk email campaigns and newsletters: campaign builder on the email template editor, list segments, send-time throttling and warmup, per-campaign analytics, Listmonk borrow notes',
  'type': 'Build', 'tier': 'sonnet', 'effort': 'medium', 'size': 'M', 'priority': 4, 'surfaces': ['Staff', 'Customer'], 'milestone': 'Campaigns and social', 'deferred': True,
  'blockedBy': ['PAP-191', 'PAP-406', 'PAP-195', 'PAP-370', 'PAP-351', 'PAP-405'], 'blocks': [],
  'goal': "Send the monthly newsletter and one-off announcements to a segment, which sequences (PAP-191) do not do: a campaign object with a subject, template (PAP-406 editor), audience segment (PAP-195), schedule and A/B subject test, sends throttled through the PAP-370 provider with warmup and suppression (PAP-405), per-campaign opens, clicks, bounces and unsubscribes, borrowing list-management patterns from the PAP-351 Listmonk spike.",
  'scope_in': ["`campaign` (status draft|scheduled|sending|sent|paused, segment snapshot, template, subject variants, schedule, throttle), `campaign_send` per recipient with status; sending job in batches through PAP-370 with per-tenant hourly caps and warmup stages (PAP-405)", "Builder page: pick segment (with live count), edit template with merge fields, test send, schedule; campaign report with rates and a link map; unsubscribe and preference links mandatory (PAP-187 WP0)", "Consent: only `marketing` consent recipients; suppression applied at send time"],
  'scope_out': ['SMS bulk (v0.3)', 'Deliverability consulting'],
  'spec': ['Segment membership is frozen at send start; late additions go to the next campaign', 'A/B subject test sends to 20 percent, picks the winner by open rate after 2 hours, then sends the rest', 'Complaint rate above 0.1 percent pauses the campaign and alerts (feeds platform-ops reputation guard)'],
  'provides': "campaign tables and sending job, builder and report pages, `campaign.sent|paused` events",
  'consumes': "sequences and template editor (PAP-191, PAP-406), segments (PAP-195), email package (PAP-370), compliance and warmup (PAP-405), consent (PAP-187), Listmonk notes (PAP-351)",
  'consumed_by': "engagement announcements (link campaigns), assistant drafting (campaign copy), platform-ops abuse controls (reputation)",
  'dod': ['Newsletter to a 500-contact demo segment sends throttled in the sandbox with an A/B subject; report shows rates; suppression and unsubscribe proven'],
  'tests': {'Unit': 'throttle math; A/B winner selection; freeze', 'Integration': 'batch sending with provider fixtures; complaint pause'},
  'demo': "Build the October newsletter for the demo salon, test send, schedule it, watch the batches go and the report fill in.",
  'edge': ['Template merge field missing for a contact: fallback text per field; the report lists affected recipients'],
  'deps': 'PAP-191, PAP-406, PAP-195, PAP-370, PAP-405 (hard), PAP-351, PAP-187 (soft).',
  'builder': 'Beacon', 'reviewer': 'Sentinel (Code Reviewer)',
 },
]
