from gen_common import trio

K = 'commerce'
MS = ['Commerce contract and catalog', 'Orders, POS, purchasing, projects and HR', 'Operations packs, marketplace and swap']

PROJECT = {
    'key': K,
    'name': 'Commerce, Operations & Vertical Packs',
    'lead': 'Ledger',
    'phase': 'P2',
    'description': 'The operational core that turns the finance plumbing into runnable businesses: products, variants and inventory; orders, fulfilment and returns; a POS mode with Stripe Terminal; purchasing and accounts payable; projects, time tracking and time-and-materials billing; HR core (directory, time-off, shifts, timesheets to payroll); assets and work orders; tenant-to-customer subscriptions; a two-sided marketplace model; and eleven more vertical packs on the pack format.',
    'content': """Goal: Business Core (PAP-175 to PAP-186) gives every tenant a ledger, invoices, Stripe and payroll; it does not give a retailer a product, a restaurant an order, a plumber a work order, an agency a timesheet or a landlord a lease. "One-size-fits-all software that adapts to every type of business" needs the operational objects those businesses run on, and the five packs in PAP-427 (agency, retail, SaaS, clinic, restaurant) can only be as deep as the objects underneath them. This project adds those objects as one module and then authors the packs on top: a commerce and operations domain model mapped onto `fin_*` (PAP-175) and Stripe products (PAP-177); catalog and inventory with an append-only stock movement ledger; orders and fulfilment with returns posting through PAP-394; a POS mode on the kiosk shell (PAP-23) with Stripe Terminal and the offline outbox; purchasing and AP with three-way match and approvals; projects, time entries and time-and-materials invoicing on the PAP-395 documents; HR core on `fin_employee` (PAP-399) with time-off, shifts on the scheduling availability shape and timesheets feeding payroll runs (PAP-400); assets and work orders for trades, field service and property management; tenant-to-customer subscription plans on Connect (distinct from PAP-177, which bills the tenant); a two-sided marketplace model with split payments; and packs wave 2 (salon, gym, law, real estate) and wave 3 (ecommerce, nonprofit, school, church, construction, property management, trades) with a pack conformance suite in CI. Non-goals in v0.2: shipping carrier rate shopping beyond a label port, manufacturing and BOMs, multi-warehouse transfer optimisation, full ATS, benefits administration.

## Contract

**Provides**

* `@paperos/contract-commerce`: `CatalogPort` (`products`, `variants`, `priceLists`, `resolvePrice`), `InventoryPort` (`stock`, `move`, `reserve`, `release`, `count`), `OrderPort` (`create`, `pay`, `fulfil`, `return`, `refund`), `PosPort` (`session`, `sale`, `tender`, `closeShift`) with `TerminalPort`, `PurchasingPort` (`po`, `receive`, `bill`, `match`), `ProjectsPort` (`projects`, `timeEntries`, `timer`, `invoiceFromTime`), `HrPort` (`directory`, `timeOff`, `shifts`, `timesheets`, `toPayroll`), `AssetsPort` (`assets`, `schedules`, `workOrders`), `SubscriptionsPort` (tenant→customer plans), `MarketplacePort` (`vendors`, `listings`, `split`, `payouts`), `PackPort` (`apply`, `lint`, `conformance`); slots `portal.orders`, `record.panel.tabs.stock`, `dashboard.blocks.commerce`, `pos.tender.methods`.
* Events: `product.updated`, `stock.moved|low`, `order.created|paid|fulfilled|returned|refunded`, `pos.sale.completed|shift.closed`, `po.issued|received`, `bill.approved|paid`, `time.entry.logged`, `timesheet.approved`, `timeoff.requested|approved`, `shift.published`, `workorder.created|completed`, `subscription.customer.*`, `vendor.payout.created`.
* Posting rules registered with PAP-394: `order.paid`, `order.refunded`, `stock.received`, `bill.approved`, `bill.paid`, `subscription.invoice.paid`, `marketplace.split`.

**Requires**

* business-core: finance model (PAP-175), Stripe client and Billing (PAP-177), Connect (PAP-181), Tax (PAP-182), ledger and posting rules (PAP-179, PAP-392 to PAP-394), documents and Checkout (PAP-395 to PAP-397), payroll adapter and employee sync (PAP-398 to PAP-400), reports (PAP-183).
* tables: datasets, grid, calendar, timeline, Gantt (PAP-161, PAP-165, PAP-344 to PAP-346), record surface (PAP-333), automations (PAP-174), field types (PAP-338 to PAP-340).
* data-layer: jobs (PAP-43), idempotency (PAP-304), files (PAP-37), audit (PAP-38), recurrence engine, offline outbox (PAP-272, PAP-148).
* identity: audiences including `vendor` (PAP-55), portal shell (PAP-62), permission engine (PAP-59).
* workflows: approvals framework, forms runtime (checklists), e-sign (estimates). engagement: scheduling availability shape (shifts), loyalty and memberships (POS tenders). app-shell: kiosk mode (PAP-23), native camera and scanner (PAP-260). design-system: labels, barcodes and QR (`r4/design-system/labels-barcodes-qr`), print kit (PAP-235). migration: pack format and applier (PAP-426), template gallery (PAP-428), business profile (PAP-126). pm-linear: PM entities for project tasks (PAP-100).

**Consumed by**

* business-core reports (COGS, inventory valuation, AP aging depth), growth (orders and subscriptions as CRM activity and segment attributes), engagement (loyalty earn on orders, bookings consume HR shifts), assistant (order and stock lookups), platform-ops (commerce metrics in tenant health), migration (packs wave 2 and 3 in the gallery, Shopify and Square import mappings in v0.3).

**Owner**: Ledger leads; Ledger builds catalog, orders, POS, purchasing, subscriptions and marketplace; Nova builds projects, HR and assets on the tables engine; Scout authors packs with the Template Packager; Sentinel reviews every money path. Milestones: Commerce contract and catalog (2026-10-01), Orders, POS, purchasing, projects and HR (2026-10-09, deferred v0.2), Operations packs, marketplace and swap (2026-10-16, deferred v0.2).""",
    'milestones': [
        {'name': MS[0], 'targetDate': '2026-10-01', 'description': 'Domain model, contract v0.1, catalog and inventory with the stock movement ledger.'},
        {'name': MS[1], 'targetDate': '2026-10-09', 'description': 'Deferred (v0.2). Orders and fulfilment, POS mode, purchasing and AP, projects and time billing, HR core, assets and work orders.'},
        {'name': MS[2], 'targetDate': '2026-10-16', 'description': 'Deferred (v0.2). Customer subscriptions, marketplace model, packs wave 2 and 3 with pack conformance, conformance suite and kernel wiring.'},
    ],
}

ISSUES = [
 {
  'key': f'r4/{K}/domain-model', 'title': 'Specify the commerce and operations domain model: product, variant, price list, stock location and movement, order and fulfilment, purchase order and bill, project and time entry, shift, asset and work order, mapped to fin_* and Stripe',
  'type': 'Spec', 'tier': 'fable', 'size': 'M', 'priority': 2, 'surfaces': ['Developer', 'Staff'], 'milestone': MS[0], 'deferred': False,
  'blockedBy': ['PAP-175', 'PAP-177', 'PAP-302', 'PAP-395', 'PAP-394', 'PAP-126'], 'blocks': [f'r4/{K}/contract-publish', f'r4/{K}/catalog-inventory'],
  'goal': "Draw the operational objects every business type shares and how they attach to the finance model: which objects are `fin_party`s, which lines become `fin_document` lines, which movements post to the ledger and through which PAP-394 rules, how Stripe products and prices mirror the catalog, and which terminology (PAP-126) renames them per industry, so eleven packs can be authored without inventing new tables.",
  'scope_in': [
    "`docs/commerce/model.md` with an ER diagram and Zod schemas in the contract: `Product` (`kind good|service|digital|bundle`, `taxCode`, `trackInventory`), `Variant` (`sku`, `barcode`, options, `stripePriceId?`), `PriceList` (currency, audience, validity, rules), `StockLocation`, `StockMovement` (append-only: `receipt|sale|return|adjustment|transfer|count`, qty, cost `Money`, source `EntityRef`), `Order` and `OrderLine` (channel `portal|pos|manual|marketplace`, status machine), `Fulfilment` (pickup, delivery, shipment with label ref), `Return`, `PurchaseOrder`, `Receipt`, `VendorBill`, `Project`, `TimeEntry`, `Shift`, `TimeOffRequest`, `Timesheet`, `Asset`, `MaintenanceSchedule`, `WorkOrder`, `CustomerSubscription`, `Vendor` (marketplace), `Listing`, `Payout`",
    "Finance mapping table: which object creates or references `fin_party` (customers, vendors, employees are parties per PAP-175), which flows create `fin_document`s (order → invoice or receipt, bill → AP document, time → invoice), inventory valuation (weighted average, COGS on sale) and the posting rules to register",
    "Stripe mapping: `Product`/`Variant` ↔ Stripe Product/Price on the platform or connected account (PAP-177, PAP-181); sync direction rules (PaperOS is the source; Stripe ids stored); Tax codes (PAP-182)",
    "Terminology defaults per industry in `industries.yaml` (PAP-126): product → dish, service, treatment, unit; order → ticket, job, case; vendor → supplier, subcontractor",
  ],
  'scope_out': ['Implementation', 'UI', 'Manufacturing, BOMs, multi-currency price lists beyond `r4/business-core/fx-rates`'],
  'spec': [
    'Stock is never a stored number of record: `onHand` is the sum of movements per location, cached and rebuilt like ledger balances (PAP-394 `rebuildBalances` pattern); reservations are movements of kind `reserve` with expiry',
    'Orders and bills own no money logic: they produce `fin_document`s and payments flow through PAP-396; refunds are credit notes plus Stripe refunds; COGS posts at fulfilment with the movement\'s cost',
    'Projects reuse PM entities (PAP-100) for tasks; a `Project` is a billing and reporting container over them; time entries reference tasks optionally',
    'Shifts reuse the scheduling `AvailabilityRule` shape (engagement) so a staff shift and a bookable slot are one truth; timesheets aggregate time entries and shifts for payroll (PAP-400 inputs)',
    'Every table has `tenant_id`, RLS, audit trigger and an `EntityRef` route registered for the assistant and search; every status machine is drawn and its events named',
  ],
  'provides': "`docs/commerce/model.md`, ER diagram, Zod schemas for the objects above, finance and Stripe mapping tables, posting rule list, terminology defaults",
  'consumes': "finance model (PAP-175), Stripe Billing and Connect (PAP-177, PAP-181), `Money` (PAP-302), documents (PAP-395), posting rules (PAP-394), business profile (PAP-126), PM entities (PAP-100)",
  'consumed_by': f"every issue in this project; PAP-183 (inventory valuation and COGS reports), PAP-427 packs (objects available), growth (order activity), assistant tools",
  'dod': ['Document merged with ADR; schemas exported; migration for the tables with RLS and harness enrolment; three worked flows (retail sale with stock, agency time-to-invoice, plumber work order to invoice) as JSON fixtures that validate and a posting trace for each'],
  'tests': {
    'Unit': 'schema fixtures; status machines as pure reducers with exhaustive transition tests; stock sum invariant on fixtures',
    'Review': 'Ledger (Bookkeeper) checks the posting rule list against PAP-394; Sentinel checks that no object stores card or bank data (PAP-359)',
  },
  'demo': "Walk the retail flow: variant with stock in two locations, POS sale reserving then consuming stock, the receipt document, the COGS and revenue postings, and a return reversing them.",
  'edge': ['Service-only business (agency): inventory tables exist but stay empty and hidden by the module toggle for that pack', 'Same SKU sold on marketplace and directly: one variant, two channels; the marketplace split is a posting rule, not a second product'],
  'deps': 'PAP-175, PAP-177 (hard), PAP-302, PAP-395, PAP-394 (hard), PAP-126, PAP-100 (soft).',
  'builder': 'Ledger', 'reviewer': 'Sentinel (Security Auditor)', 'tenant_data': False, 'module_edge': False,
 },
 {
  'key': f'r4/{K}/catalog-inventory', 'title': 'Build catalog and inventory: products, variants, price lists, stock per location with the append-only movement ledger, reservations, counts, low-stock alerts, barcodes and Stripe price sync',
  'type': 'Build', 'tier': 'opus', 'size': 'M', 'priority': 2, 'surfaces': ['Staff', 'Customer'], 'milestone': MS[0], 'deferred': False,
  'blockedBy': [f'r4/{K}/domain-model', f'r4/{K}/contract-publish', 'PAP-177', 'PAP-338', 'PAP-333', 'PAP-136'], 'blocks': [f'r4/{K}/orders-fulfilment', f'r4/{K}/pos-mode', f'r4/{K}/purchasing-ap'],
  'goal': "Implement the catalog and stock half of the model: products and variants with options, images and barcodes, price lists per audience and currency, stock per location derived from an append-only movement ledger with reservations and counts, low-stock alerts through notifications, and Stripe Product and Price sync so Checkout and subscriptions reference real catalog entries.",
  'scope_in': [
    "`packages/commerce/src/catalog/` and `inventory/`: tables from the model; `CatalogPort` (`resolvePrice(variant, audience, currency, qty, date)` applying price list rules and quantity breaks) and `InventoryPort` (`move`, `reserve` with TTL and `release`, `count` with variance movements, `stock(variant, location)` cached view); datasets `products`, `variants`, `stock_levels`, `stock_movements` registered for the grid (PAP-165) with the record surface (PAP-333) and a `stock` record tab",
    "Console pages `/commerce/products` (grid, product editor with variant matrix generator, images via PAP-37 with variants), `/commerce/inventory` (levels by location, adjust, transfer, count sheet), spec files for each",
    "Barcodes: `barcode` field type from `r4/design-system/labels-barcodes-qr` with scanner input (PAP-260 or keyboard wedge), label printing for shelf and product labels",
    "Stripe sync job: create or update Product and Price on the platform or the connected account (PAP-181 setting) with idempotency; archived variants archive prices; `stripePriceId` stored; alerts kind `stock.low` via PAP-136 when `onHand − reserved < reorderPoint`",
  ],
  'scope_out': ['Orders (next issue)', 'Purchase receipts create movements but live in purchasing', 'Serial and lot tracking (v0.3)'],
  'spec': [
    'Movements are immutable rows with a trigger rejecting UPDATE and DELETE (PAP-392 pattern); corrections are new `adjustment` movements with a reason; `onHand` cache rebuilt nightly and verified against the sum',
    'Reservations expire (default 15 minutes for carts, configurable per channel); a fulfilment converts the reservation into a `sale` movement in one transaction',
    'Weighted-average cost per variant per location updates on receipts; sale movements carry the cost at the moment of sale for COGS postings (owned by orders)',
    'Price resolution is pure and testable: list precedence, audience match, validity window, quantity breaks, tax-inclusive flag per price list',
    'Variant matrix generation is bounded (200 variants per product) with a clear message beyond',
  ],
  'provides': "`CatalogPort` and `InventoryPort` default adapters, tables and datasets, console pages, barcode field type usage, Stripe sync job, `product.updated`, `stock.moved|low` events",
  'consumes': "the model and contract, Stripe client (PAP-177, PAP-181), field types (PAP-338), record surface (PAP-333), notifications (PAP-136), files (PAP-37), grid (PAP-165), labels and scanner (`r4/design-system/labels-barcodes-qr`, PAP-260)",
  'consumed_by': f"`r4/{K}/orders-fulfilment`, `r4/{K}/pos-mode`, `r4/{K}/purchasing-ap`, `r4/{K}/customer-subscriptions` (prices), engagement loyalty (order lines), packs wave 2 and 3, PAP-183 valuation report",
  'dod': ['Demo retail tenant with 50 products and 300 variants across two locations; a 500-movement fixture sums to the cached levels; concurrent reservations for the last unit yield one success; Stripe test account shows synced prices; low-stock alert fires; label printed'],
  'tests': {
    'Unit': 'price resolution over 40 fixtures; matrix generation; weighted-average cost; movement immutability trigger',
    'Integration': 'reserve and release under concurrency; count variance movements; Stripe sync idempotency with recorded fixtures',
    'E2E': 'product editor, variant matrix, scan a barcode into the inventory adjust form; screenshots',
  },
  'demo': "Create a T-shirt with size and colour variants, receive 20 units into the warehouse, scan one at the counter to check stock, adjust a count, and open Stripe test mode to show the synced prices.",
  'edge': ['Variant deleted with stock on hand: refused; must be adjusted to zero or archived with a note', 'Two locations count the same variant simultaneously: each count is its own movement; the level is the sum; no lost update'],
  'deps': f"`r4/{K}/domain-model` and `r4/{K}/contract-publish` (hard), PAP-177 (hard: sync), PAP-338, PAP-333, PAP-136 (soft), `r4/design-system/labels-barcodes-qr` (soft: text fallback).",
  'builder': 'Ledger', 'reviewer': 'Sentinel (Edge Case Hunter)',
 },
 {
  'key': f'r4/{K}/orders-fulfilment', 'title': 'Build orders and fulfilment: cart to order state machine, payment via Checkout on platform or connected account, pickup, delivery and shipping label port, returns and refunds with ledger postings, portal order history',
  'type': 'Build', 'tier': 'opus', 'size': 'L', 'priority': 4, 'surfaces': ['Customer', 'Staff'], 'milestone': MS[1], 'deferred': True,
  'blockedBy': [f'r4/{K}/catalog-inventory', 'PAP-396', 'PAP-394', 'PAP-182', 'PAP-395', 'PAP-136'], 'blocks': [f'r4/{K}/pos-mode', f'r4/{K}/marketplace-model'],
  'goal': "Sell things end to end: a cart and order state machine (`draft → placed → paid → fulfilling → fulfilled → closed`, with `cancelled`, `returned`, `refunded` branches), payment through PAP-396 Checkout on the platform or the tenant's connected account with Stripe Tax, fulfilment by pickup, delivery or shipment through a `ShippingLabelPort`, returns with restocking movements, refunds as credit notes plus Stripe refunds, and a portal order history.",
  'scope_in': [
    "`OrderPort`: `create` (from portal cart, staff, POS, marketplace) reserving stock, `pay` (Checkout session or manual payment PAP-397), `fulfil` (per line, converts reservations to sale movements, posts COGS), `return` (RMA, inspection, restock or write-off movement), `refund` (credit note PAP-395 + Stripe refund with idempotency); order → `fin_document` receipt or invoice per tenant setting",
    "Fulfilment kinds: `pickup` (ready notification and pickup code), `delivery` (routes as a dataset for the map view PAP-170, driver assignment), `shipment` (`ShippingLabelPort` with a `manual` adapter and an EasyPost adapter behind a flag; tracking number and events)",
    "Console `/commerce/orders` (grid with status tabs, order detail with timeline, fulfil and return drawers, pick list print via the print kit), portal `/portal/orders` (history, detail, tracking, return request), notification kinds `order.*`",
    "Posting rules registered with PAP-394: `order.paid` (revenue, tax, fees, receivable), `order.fulfilled` (COGS/inventory), `order.refunded`, `return.restocked`",
  ],
  'scope_out': ['Storefront theme (portal pages are the storefront in v0.2; a public shop is v0.3)', 'Carrier rate shopping', 'Subscriptions (own issue)'],
  'spec': [
    'Order totals are computed server-side from resolved prices and Stripe Tax (PAP-182) at placement; a price change after placement never changes an order',
    'Payment completion is webhook-only (SAQ-A, PAP-359); an order waiting for payment releases its reservations after the channel TTL',
    'Partial fulfilment and partial refund are first-class; refunds cannot exceed captured amounts minus prior refunds (server-enforced)',
    'Returns require an RMA; restock or write-off is a movement with cost; refund method follows the original tender',
    'Every transition is idempotent by `(orderId, transition, key)` and emits its event; the timeline shows actor and reason',
  ],
  'provides': "`OrderPort` default adapter, `ShippingLabelPort` with two adapters, tables and datasets, console and portal pages, posting rules, notification kinds, `order.*` events",
  'consumes': "catalog and inventory, Checkout and manual payments (PAP-396, PAP-397), documents and credit notes (PAP-395), posting rules (PAP-394), Stripe Tax (PAP-182), notifications (PAP-136), map view (PAP-170), print kit (PAP-235), portal shell (PAP-62)",
  'consumed_by': f"`r4/{K}/pos-mode`, `r4/{K}/marketplace-model`, engagement loyalty (`order.paid` earn), growth (orders as CRM activity), assistant (order lookups), packs (retail, restaurant, ecommerce)",
  'dod': ['Portal order paid in test mode → fulfilled by shipment with a manual label → partial return restocked → partial refund; ledger trial balance reconciles; a delivery route renders on the map; screenshots of console and portal at three widths'],
  'tests': {
    'Unit': 'state machine exhaustive; totals and tax with recorded Stripe Tax fixtures; refund cap enforcement',
    'Integration': 'webhook idempotency; reservation TTL release; posting traces per rule; concurrent fulfilment of the same line refused',
    'E2E': 'portal checkout at 375; staff fulfil and return flows; pick list print',
  },
  'demo': "Order two T-shirts in the portal, pay in test mode, fulfil from the console with a printed pick list and label, return one, refund it, and show the ledger entries and stock movement for each step.",
  'edge': ['Stock oversold by a manual order (staff override): the order is placed with a backorder flag and the low-stock alert escalates; fulfilment waits for receipt', 'Refund after the connected account has insufficient balance: Stripe fails; the refund stays `pending` with a staff notification and retry'],
  'deps': f"`r4/{K}/catalog-inventory` (hard), PAP-396, PAP-395, PAP-394 (hard), PAP-182 (hard for tax), PAP-397, PAP-136, PAP-170 (soft).",
  'builder': 'Ledger', 'reviewer': 'Sentinel (Security Auditor)',
 },
 {
  'key': f'r4/{K}/pos-mode', 'title': 'Build POS mode: kiosk and tablet layout, cart and tenders (Terminal, cash, gift card, points, manual), Stripe Terminal adapter, offline sales queue, receipts and shift close with Z-report',
  'type': 'Build', 'tier': 'opus', 'size': 'M', 'priority': 4, 'surfaces': ['Staff', 'Customer'], 'milestone': MS[1], 'deferred': True,
  'blockedBy': [f'r4/{K}/orders-fulfilment', 'PAP-23', 'PAP-148', 'PAP-181', 'PAP-260', 'PAP-235'], 'blocks': [],
  'goal': "Sell at the counter: a POS mode on the kiosk shell (PAP-23) sized for tablets and touch, a fast cart with scanner input, tenders through a `TerminalPort` (Stripe Terminal adapter, cash, gift card and loyalty points from engagement, manual), offline sales queued through the PAP-148 outbox and reconciled later, printed or emailed receipts, and shift open and close with a Z-report.",
  'scope_in': [
    "Route `/pos` (spec) in kiosk mode: product grid with categories and search, barcode scan (PAP-260 or wedge), cart with line discounts within permission limits, customer attach (CRM), tender screen; `PosPort.session` (device registration, cash drawer float), `sale` (creates and pays an order with channel `pos`), `tender`, `closeShift`",
    "`TerminalPort`: `stripe-terminal` (server-driven readers via PAP-181 connected account, connection token endpoint, reader status), `cash` (change calculation, drawer events), `giftCard` and `points` delegating to engagement `LoyaltyPort`, `manual`; split tenders",
    "Offline: sales for cash and gift card tenders queue in the outbox with local stock decrement; card tenders require connectivity (reader needs it too); replay is idempotent by sale id; a banner shows queued count (PAP-148 indicator)",
    "Receipts through the print kit (PAP-235) to a receipt printer (ESC/POS via browser USB or a PDF fallback) or email/SMS; shift close: counted cash vs expected, variance posting, Z-report PDF; `pos.sale.completed|shift.closed` events",
  ],
  'scope_out': ['Table service and kitchen display for restaurants (restaurant pack v0.3 extension)', 'Multi-register cash management beyond per-device shifts'],
  'spec': [
    'Cart operations are local-first and under 50 ms; price resolution uses a cached price list snapshot refreshed on shift open and on `product.updated` events',
    'Card data never touches PaperOS (SAQ-A, PAP-359): the reader talks to Stripe; the API only exchanges connection tokens and payment intent ids',
    'Offline sales cannot exceed the cached stock for goods flagged `strictStock`; others allow negative with a flag for reconciliation',
    'Discount authority comes from the permission engine (PAP-59) with a manager PIN override path audited',
    'Shift reports post cash variance through PAP-394 and are immutable once closed',
  ],
  'provides': "`PosPort` and `TerminalPort` with adapters, `/pos` kiosk route, offline sale queue, receipts, shift and Z-report, `pos.*` events, slot `pos.tender.methods`",
  'consumes': "orders, kiosk mode (PAP-23), offline outbox and indicator (PAP-148, PAP-272), Connect (PAP-181), scanner (PAP-260), print kit (PAP-235), loyalty and gift cards (engagement), permission engine (PAP-59), posting rules (PAP-394)",
  'consumed_by': "packs (retail, restaurant, salon retail shelf), engagement (member pricing and loyalty at POS), platform-ops (device health)",
  'dod': ['Tablet demo: scan three items, attach a customer, split cash and Terminal (simulated reader), print a receipt, go offline and sell for cash, come back and reconcile, close the shift with a Z-report; postings reconcile'],
  'tests': {
    'Unit': 'cart math and discounts; change calculation; split tenders; offline stock guard',
    'Integration': 'Terminal connection token and payment intent flow with the Stripe simulated reader; outbox replay idempotency; shift close variance posting',
    'E2E': 'touch-only flow at 768 and 1024 landscape; scanner wedge input; receipt PDF snapshot',
  },
  'demo': "Ring up a sale on the tablet with a simulated Terminal reader, then pull the network cable, sell two more items for cash, reconnect and watch them sync, and close the shift.",
  'edge': ['Reader disconnects mid-payment: the intent is cancelled or confirmed by webhook; the cart waits with a clear status and never double-charges', 'Same variant edited (price) during a shift: the cached price holds until shift end unless the cashier refreshes; the change is flagged on the Z-report'],
  'deps': f"`r4/{K}/orders-fulfilment` (hard), PAP-23, PAP-148 (hard), PAP-181 (hard), PAP-260, PAP-235 (soft), engagement loyalty (soft: tenders hidden when absent).",
  'builder': 'Ledger', 'reviewer': 'Sentinel (Security Auditor)',
 },
 {
  'key': f'r4/{K}/purchasing-ap', 'title': 'Build purchasing and accounts payable: purchase orders, receiving into stock, vendor bills with OCR capture, three-way match, approval policies, bill payment scheduling and AP postings',
  'type': 'Build', 'tier': 'opus', 'size': 'M', 'priority': 4, 'surfaces': ['Staff'], 'milestone': MS[1], 'deferred': True,
  'blockedBy': [f'r4/{K}/catalog-inventory', 'PAP-185', 'PAP-394', 'PAP-183', 'PAP-395'], 'blocks': [],
  'goal': "Run the buying side: purchase orders to vendors (`fin_party` vendors from PAP-175), receiving that creates stock movements at cost, vendor bills captured by upload with the PAP-185 receipt OCR, three-way match (PO, receipt, bill) with tolerances, approval through the workflows approvals framework, payment scheduling with runs, and AP postings so PAP-183's AP aging has real data.",
  'scope_in': [
    "`PurchasingPort`: `po` (draft, issue by email PDF via the print kit, acknowledge), `receive` (partial receipts create `receipt` movements with landed cost allocation), `bill` (create from upload with OCR line extraction reusing PAP-185, or from PO), `match` (quantity and price tolerances, exceptions queue), `schedulePayment` (due dates, early-payment terms, batch payment run marking bills paid with a manual or Stripe payout reference)",
    "Console pages `/commerce/purchasing` (POs grid and editor, receiving screen with scanner, bills inbox with OCR review side by side, match exceptions, payment runs) with specs",
    "Approvals: policy keys `po.issue` and `bill.approve` with Money thresholds through `r4/workflows/approvals-framework`; segregation of duties enforced (receiver ≠ approver)",
    "Posting rules: `stock.received` (inventory asset vs goods-received-not-invoiced), `bill.approved` (expense or inventory vs AP), `bill.paid` (AP vs cash); reports registered for PAP-183 AP aging drill-down",
  ],
  'scope_out': ['Automated vendor payments through a payments API (v0.3; bills are marked paid with a reference)', 'Vendor portal (marketplace issue covers vendor audience)'],
  'spec': [
    'Three-way match runs on bill creation and on every receipt; tolerances per tenant (default 2 percent price, 0 quantity); mismatches block approval until resolved with a reason',
    'Landed costs (freight, duty) allocate across received lines by value or quantity and adjust weighted-average cost',
    'Bills are `fin_document`s of kind `bill` (PAP-395 model) with vendor numbering; duplicate detection on vendor + reference + amount',
    'Payment runs are immutable once executed; reversing requires a new run',
  ],
  'provides': "`PurchasingPort` default adapter, tables, console pages, approval policy keys, posting rules, `po.*` and `bill.*` events, AP datasets",
  'consumes': "catalog and inventory, receipt OCR (PAP-185), posting rules (PAP-394), documents (PAP-395), AP aging report (PAP-183), approvals framework, print kit (PAP-235), scanner (PAP-260)",
  'consumed_by': "PAP-183 (AP aging depth), packs (retail, restaurant, construction, trades), platform-ops (spend metrics)",
  'dod': ['Demo: issue a PO, receive partially with a scanner, upload the vendor bill PDF, OCR proposes lines, match flags a price variance, manager approves with a reason, payment run marks it paid; AP aging shows it; postings reconcile'],
  'tests': {
    'Unit': 'match tolerances; landed cost allocation; duplicate detection; payment run immutability',
    'Integration': 'partial receipts and cost updates; approval segregation; posting traces',
  },
  'demo': "Buy 100 mugs: PO to the supplier, receive 60, upload the bill for 60 at a slightly higher price, watch the match exception, approve, schedule payment, and open AP aging.",
  'edge': ['Bill arrives before any receipt (services): match degrades to two-way and the policy may require a second approver', 'Vendor changes bank details on a bill: flagged as a fraud signal (PAP-356 event) and requires re-verification before payment'],
  'deps': f"`r4/{K}/catalog-inventory` (hard), PAP-185, PAP-394, PAP-395 (hard), PAP-183 (soft), `r4/workflows/approvals-framework` (hard for approvals; a simple role gate as fallback).",
  'builder': 'Ledger', 'reviewer': 'Sentinel (Security Auditor)',
 },
 {
  'key': f'r4/{K}/projects-time-billing', 'title': 'Build projects, time tracking and time-and-materials billing: projects over PM tasks, time entries and timers, billable rates and budgets, retainers, expenses to projects, time to invoice, utilisation reports',
  'type': 'Build', 'tier': 'sonnet', 'effort': 'high', 'size': 'M', 'priority': 4, 'surfaces': ['Staff', 'Customer'], 'milestone': MS[1], 'deferred': True,
  'blockedBy': [f'r4/{K}/domain-model', 'PAP-100', 'PAP-102', 'PAP-395', 'PAP-185', 'PAP-346'], 'blocks': [f'r4/{K}/hr-core'],
  'goal': "Make agencies, law firms, consultancies and studios billable: projects as containers over PM tasks (PAP-100), time entries with a running timer and manual entry, billable rates by person, role or project, budgets with burn alerts, retainers drawn down monthly, expenses attached to projects (PAP-185), one-click invoicing of unbilled time and expenses through PAP-395, and utilisation and profitability reports as views.",
  'scope_in': [
    "`ProjectsPort`: `projects` (client `fin_party`, budget hours or Money, rate card, retainer, status), `timeEntries` (person, task, duration, billable, rate snapshot, notes, status draft|submitted|approved|invoiced), `timer` (one running per person, multi-window aware via PAP-145), `invoiceFromTime` (grouping by project, task or person, rounding rules, write-up/down, creates PAP-395 invoice lines and marks entries invoiced)",
    "Pages: `/projects` (grid and Gantt PAP-346 over tasks), project detail with budget burn, time tab, expenses tab, unbilled summary; `/time` (weekly timesheet grid, timer bar in the shell `shell.header.actions` slot); portal `/portal/projects` for clients (status, approved time, invoices)",
    "Rate cards: precedence person-on-project > role-on-project > project default > person default; currency from the project; retainers as prepaid `fin_document`s drawn down by posting rules",
    "Reports as datasets: utilisation (billable vs available from HR shifts when present), realisation, project profitability (revenue vs cost rates plus expenses), budget alerts via notifications",
  ],
  'scope_out': ['Resource planning and capacity forecasting (v0.3)', 'Trust accounting for law firms (pack adds a restricted ledger account set; IOLTA rules v0.3)'],
  'spec': [
    'Time entries snapshot the rate at approval so later rate changes do not alter unbilled value; write-ups and write-downs are explicit lines with reasons',
    'Timers survive reloads and multiple windows (PAP-145) and stop automatically after 12 hours with a review prompt',
    'Invoicing groups per tenant setting; invoiced entries become immutable; a credit note un-invoices them explicitly',
    'Client portal shows only approved, billable entries unless the project allows detail',
  ],
  'provides': "`ProjectsPort` default adapter, tables and datasets, projects and time pages, timer slot fill, portal pages, posting rules for retainers, `time.entry.logged`, `project.*` events",
  'consumes': "PM entities and boards (PAP-100, PAP-102), Gantt (PAP-346), documents (PAP-395), expenses (PAP-185), window bus (PAP-145), notifications (PAP-136), HR shifts (soft)",
  'consumed_by': f"`r4/{K}/hr-core` (timesheets), packs (agency, law, construction), growth (client activity), assistant (\"how many hours on Acme this month?\")",
  'dod': ['Agency demo: two people log time via timer and timesheet across three projects, one retainer; approve; invoice unbilled time grouped by task with a write-down; utilisation and profitability views render; client sees approved time in the portal'],
  'tests': {
    'Unit': 'rate precedence; rounding rules; budget burn; timer auto-stop',
    'Integration': 'invoice from time marks entries and reverses on credit note; retainer drawdown postings; multi-window timer',
  },
  'demo': "Start a timer on a task from one window, stop it from another, submit the week, approve as a manager, invoice the project with 15-minute rounding and show the retainer drawdown.",
  'edge': ['Entry logged against a task moved to another project: the entry keeps its project unless re-assigned explicitly; report shows the mismatch', 'Person without a rate: entry is non-billable with a warning until a rate exists'],
  'deps': f"`r4/{K}/domain-model` (hard), PAP-100, PAP-395 (hard), PAP-102, PAP-346, PAP-185, PAP-145 (soft).",
  'builder': 'Nova', 'reviewer': 'Sentinel (Code Reviewer)',
 },
 {
  'key': f'r4/{K}/hr-core', 'title': 'Build HR core: employee directory and profiles on fin_employee, time-off policies and requests with approvals, shift scheduling on the availability shape, clock-in, timesheets and export to payroll runs',
  'type': 'Build', 'tier': 'sonnet', 'effort': 'high', 'size': 'M', 'priority': 4, 'surfaces': ['Staff'], 'milestone': MS[1], 'deferred': True,
  'blockedBy': [f'r4/{K}/projects-time-billing', 'PAP-399', 'PAP-400', 'PAP-344', 'PAP-59'], 'blocks': [],
  'goal': "Give every business the staff-facing basics payroll assumes: an employee directory and profile on `fin_employee` (PAP-399) with documents and emergency contacts, time-off policies (accrual, carryover, blackout) with requests approved through the approvals framework, shift scheduling that reuses the engagement availability shape and renders on the calendar (PAP-344), clock-in and out (kiosk or mobile with geofence), timesheets that aggregate entries and shifts, and an export that becomes the PAP-400 payroll run inputs.",
  'scope_in': [
    "`HrPort`: `directory` (profiles, roles, managers, documents via PAP-37 with restricted audience `hr`), `timeOff` (policies, balances, requests, approvals via policy key `timeoff.approve`), `shifts` (templates, publish, swap requests, open shifts claim), `timesheets` (weekly, from clock events, time entries and shifts; approve), `toPayroll(period)` producing the hours and earnings inputs PAP-400 consumes",
    "Pages: `/hr/people` (directory grid and profile), `/hr/time-off` (calendar overlay and requests), `/hr/schedule` (week view on PAP-344 with drag, coverage counts, labour cost estimate), `/hr/timesheets`; staff self-service under `/me` (balances, request, my shifts, clock)",
    "Clock: kiosk mode (PAP-23) with PIN and photo, mobile with geofence (PAP-260 geolocation) and offline queue (PAP-148); events feed timesheets",
    "Permissions: HR data uses attribute policies (PAP-227): managers see reports, HR sees all, employees see self; salary fields restricted to payroll roles; every access to compensation audited (PAP-38)",
  ],
  'scope_out': ['Benefits administration, recruiting and onboarding checklists beyond a workflow template (packs may add)', 'Labour-law compliance engines (overtime rules are configurable, not pre-certified)'],
  'spec': [
    'Time-off accrual runs monthly as a job with per-policy rules; balances derive from ledger-like entries (accrual, usage, adjustment) and are rebuildable',
    'Published shifts write `AvailabilityRule(kind blocked|available, source shift)` on the linked scheduling resource so bookings and shifts agree',
    'Timesheet locks after approval; changes create adjustments visible to payroll; overtime rules (daily and weekly thresholds, multipliers) configurable per tenant and jurisdiction profile (PAP-126)',
    '`toPayroll` output validates against the PAP-398 adapter contract and is reviewed with the typed-total approval (PAP-400)',
  ],
  'provides': "`HrPort` default adapter, tables, HR pages and self-service, clock flows, shift → availability bridge, payroll export, `timeoff.*`, `shift.*`, `timesheet.approved` events",
  'consumes': "employee model and payroll run (PAP-399, PAP-400, PAP-398), calendar view (PAP-344), scheduling availability shape (engagement), approvals framework, attribute policies (PAP-227), kiosk and geolocation (PAP-23, PAP-260), offline outbox (PAP-148), audit (PAP-38)",
  'consumed_by': "PAP-400 (inputs), engagement scheduling (staff availability), projects (utilisation), packs (restaurant, retail, gym, construction)",
  'dod': ['Restaurant demo: 12 employees, a two-week published schedule, two time-off requests approved, clock events from the kiosk, timesheets approved with overtime, export validated against the payroll adapter fixture; salary access audited'],
  'tests': {
    'Unit': 'accrual rules; overtime computation across week boundaries and DST; shift-to-availability bridge; geofence check',
    'Integration': 'approval flow; timesheet lock and adjustments; export validation against PAP-398 schema',
    'E2E': 'schedule drag on the calendar; self-service request on a phone; kiosk clock with PIN',
  },
  'demo': "Publish next week's schedule for the restaurant, approve a vacation that opens a shift, let another employee claim it, clock in at the kiosk, approve timesheets and export to payroll.",
  'edge': ['Employee in two roles with different rates: shifts carry the role; timesheet lines split by role for payroll', 'Clock-in without connectivity at a remote site: queued with device time and geolocation; flagged for review if the drift exceeds 5 minutes'],
  'deps': f"`r4/{K}/projects-time-billing` (soft: shares timesheet UI), PAP-399, PAP-400, PAP-398 (hard), PAP-344 (hard), PAP-59, PAP-227 (hard), engagement scheduling model (soft), PAP-23, PAP-260, PAP-148 (soft).",
  'builder': 'Nova', 'reviewer': 'Sentinel (Security Auditor)',
 },
 {
  'key': f'r4/{K}/assets-work-orders', 'title': 'Build assets and work orders: asset registry with locations and warranties, maintenance schedules on the recurrence engine, work orders with checklists, parts and labour, mobile technician flow with photos, signatures and invoicing',
  'type': 'Build', 'tier': 'sonnet', 'effort': 'medium', 'size': 'M', 'priority': 4, 'surfaces': ['Staff', 'Customer'], 'milestone': MS[1], 'deferred': True,
  'blockedBy': [f'r4/{K}/catalog-inventory', f'r4/{K}/projects-time-billing', 'PAP-260', 'PAP-170', 'PAP-395'], 'blocks': [],
  'goal': "Serve trades, field service, facilities and property management: an asset registry (equipment, units, vehicles) with locations, QR labels and warranties, maintenance schedules on the recurrence engine that generate work orders, work orders with checklists (forms runtime), parts from inventory and labour from time entries, a phone-first technician flow with photos, customer signature and status updates, and invoicing of completed work through PAP-395.",
  'scope_in': [
    "`AssetsPort`: `assets` (kind, location or property unit, customer owner `fin_party`, serial, purchase and warranty, custom fields via PAP-332), `schedules` (RRULE-based preventive maintenance creating work orders N days ahead), `workOrders` (status new|scheduled|in_progress|on_hold|completed|invoiced, assignee, scheduled window via the booking engine when present, checklist form, parts lines reserving stock, labour via time entries, photos, customer signature via e-sign or an in-app signature capture fallback)",
    "Pages: `/assets` (grid, map view PAP-170 by location, asset detail with history), `/work-orders` (board and calendar), technician mobile route `/wo/:id` (offline-capable via PAP-148: checklist, camera PAP-260, parts scan, signature, complete); customer portal shows their assets and work order history",
    "Invoicing: `completeAndInvoice` builds a PAP-395 invoice from parts (catalog prices) and labour (rate card) with the checklist and photos attached; estimates as quotes (PAP-395 quote → acceptance via e-sign)",
  ],
  'scope_out': ['Route optimisation and dispatch boards beyond assignment and map (v0.3)', 'IoT telemetry ingestion (webhook trigger only)'],
  'spec': [
    'Parts used on a work order are `sale` movements from the technician\'s van location or the main store; unused reserved parts release on completion',
    'Checklists are form definitions; a work order type binds a form version; completion requires required items; photos are attached to answers',
    'Preventive schedules generate work orders idempotently per `(schedule, occurrence)`; skipped occurrences are recorded',
    'Customer-facing status updates use notification kinds `workorder.scheduled|en_route|completed` with quiet hours',
  ],
  'provides': "`AssetsPort` default adapter, tables and datasets, pages and technician route, portal views, `workorder.*` events, schedule job",
  'consumes': "catalog and inventory (parts), projects (labour), recurrence engine, camera and geolocation (PAP-260), offline outbox (PAP-148), map view (PAP-170), documents and quotes (PAP-395), forms runtime and e-sign (workflows, soft), custom fields (PAP-332), booking engine (soft)",
  'consumed_by': "packs (trades, construction, property management, gym equipment), assistant (\"when was the boiler last serviced?\"), platform-ops (none)",
  'dod': ['Plumber demo: 30 assets across 10 properties on the map, a quarterly schedule generating work orders, a technician completes one on a phone offline with two photos, parts and a signature, syncs, and invoices it; portal shows the history'],
  'tests': {
    'Unit': 'schedule occurrence idempotency; checklist completion rules; parts movement and release',
    'E2E': 'technician route at 375 offline then online; map view; invoice from work order',
  },
  'demo': "Open the work-order board, take the boiler service on a phone, go offline, tick the checklist, photograph the serial plate, scan a part, get the customer's signature, reconnect, and invoice.",
  'edge': ['Asset transferred to another customer: history stays with the asset; open work orders re-bind to the new owner only with confirmation', 'Technician completes offline while the office cancels the work order: on sync the completion wins with a conflict flag (PAP-144 banner) for the office to resolve'],
  'deps': f"`r4/{K}/catalog-inventory` and `r4/{K}/projects-time-billing` (hard), PAP-260, PAP-148, PAP-170, PAP-395 (hard), `r4/data-layer/recurrence-engine` (hard), workflows forms and e-sign (soft).",
  'builder': 'Nova', 'reviewer': 'Sentinel (Edge Case Hunter)',
 },
 {
  'key': f'r4/{K}/customer-subscriptions', 'title': 'Build tenant-to-customer subscriptions: plans and recurring billing on the connected account, trials, proration, usage add-ons, dunning, portal self-service and MRR datasets, distinct from platform billing',
  'type': 'Build', 'tier': 'opus', 'size': 'M', 'priority': 4, 'surfaces': ['Customer', 'Staff'], 'milestone': MS[2], 'deferred': True,
  'blockedBy': [f'r4/{K}/catalog-inventory', 'PAP-177', 'PAP-181', 'PAP-397', 'PAP-394'], 'blocks': [],
  'goal': "Let a tenant sell subscriptions to its own customers (SaaS packs, box subscriptions, service plans, maintenance contracts): plans built from catalog prices on the tenant's connected account, trials and proration, usage add-ons, dunning and retries through PAP-397 reminders, a portal self-service page, and MRR, churn and cohort datasets, kept strictly separate from PAP-177, which bills the tenant for PaperOS.",
  'scope_in': [
    "`SubscriptionsPort`: `plans` (catalog variants with recurring prices synced to the connected account), `subscribe` (Checkout in subscription mode PAP-396 pattern on Connect, trial days, coupon), `change` (upgrade, downgrade with proration policy), `cancel` (immediate or period end, reasons), `usage` (metered add-ons via Stripe usage records, reusing the PAP-391 aggregation pattern but for the tenant's customers); webhook mapping to `customer_subscription` status",
    "Portal `/portal/subscriptions` (plan, next invoice, change, cancel, payment method via the Stripe customer portal on the connected account); console `/commerce/subscriptions` (grid, detail with timeline, manual adjustments with approval)",
    "Dunning: failed payment → PAP-397 reminder templates and retry schedule; posting rules `subscription.invoice.paid|refunded` (PAP-394) with deferred revenue recognition option (monthly release job)",
    "Datasets and dashboard blocks: MRR, new/expansion/contraction/churn, cohort retention, trial conversion; `subscription.customer.*` events for workflows and segments",
  ],
  'scope_out': ['Platform billing (PAP-177)', 'Marketplace subscriptions (v0.3)', 'Revenue recognition beyond straight-line deferral'],
  'spec': [
    'Two Stripe contexts never mix: platform-account calls for PAP-177, connected-account calls here; a lint (Semgrep, PAP-359 style) blocks `stripe.` calls in this package without the `stripeAccount` header',
    'Status is derived from webhooks; the portal shows pending changes until confirmed; proration previews come from Stripe before the change is applied',
    'Cancellation reasons feed a dataset; win-back workflows trigger on `subscription.customer.cancelled`',
    'Deferred revenue: invoice paid → deferred liability; monthly job releases straight-line; toggle per tenant with an ADR on when it is required',
  ],
  'provides': "`SubscriptionsPort` default adapter, tables and datasets, portal and console pages, dunning integration, posting rules, MRR blocks, `subscription.customer.*` events",
  'consumes': "catalog prices, Stripe client (PAP-177) with Connect (PAP-181), reminders and dunning (PAP-397), posting rules (PAP-394), Checkout (PAP-396), metering pattern (PAP-391), approvals (soft)",
  'consumed_by': "packs (SaaS, box subscriptions, maintenance plans), growth (MRR and churn as segment attributes), assistant (portal subscription questions), engagement memberships (shares the Connect subscription plumbing)",
  'dod': ['SaaS pack demo: customer subscribes with a trial in test mode, upgrades with proration preview, a failed payment fixture triggers dunning, cancels at period end; MRR block and cohort view render; lint proves no platform-context calls'],
  'tests': {
    'Unit': 'status mapping from webhook fixtures; MRR math; deferred release schedule',
    'Integration': 'Checkout subscription → webhook → active; change with proration; dunning retries; posting traces',
  },
  'demo': "Subscribe to the demo SaaS pack's Pro plan with a 14-day trial, upgrade to Team and show the proration preview, simulate a card failure and the dunning email, then open the MRR dashboard.",
  'edge': ['Connected account not fully onboarded (PAP-181 requirements due): subscriptions cannot be sold; the console shows the Stripe requirements with a link', 'Customer disputes a subscription charge: webhook marks the invoice disputed; posting rule holds funds in a dispute account until resolution'],
  'deps': f"`r4/{K}/catalog-inventory` (hard), PAP-177, PAP-181 (hard), PAP-397, PAP-394, PAP-396 (hard), PAP-391 (soft: pattern).",
  'builder': 'Ledger', 'reviewer': 'Sentinel (Security Auditor)',
 },
 {
  'key': f'r4/{K}/marketplace-model', 'title': 'Build the two-sided marketplace model: vendor accounts on Connect, vendor audience and portal, listings, split payments with platform fees, vendor payouts and statements, disputes routing',
  'type': 'Build', 'tier': 'opus', 'size': 'M', 'priority': 4, 'surfaces': ['Customer', 'Staff'], 'milestone': MS[2], 'deferred': True,
  'blockedBy': [f'r4/{K}/orders-fulfilment', 'PAP-181', 'PAP-408', 'PAP-55', 'PAP-62'], 'blocks': [],
  'goal': "Let a tenant run a marketplace (a farmers' collective, a booking marketplace, a multi-vendor shop): vendors onboard to Connect as sub-accounts of the tenant's platform, a `vendor` audience with its own portal surface, listings that are catalog products owned by a vendor, orders that split across vendors with destination charges and platform fees, payouts with monthly statements (PAP-408 pattern), and dispute routing to the vendor.",
  'scope_in': [
    "`MarketplacePort`: `vendors` (`fin_party` + Connect account via PAP-181 onboarding links, status, fee schedule, payout schedule), `listings` (product ownership, approval queue via the approvals framework, visibility), `split(order)` (per-vendor sub-orders, destination charges or separate charges and transfers, platform fee rules), `payouts` (Stripe payout events, statements PDF via the print kit, ledger postings `marketplace.split` and `vendor.payout`)",
    "Vendor portal `/vendor` (spec) on the PAP-62 shell pattern with audience `vendor` (PAP-55): listings, orders to fulfil, payouts and statements, disputes; staff console `/commerce/marketplace` (vendors, approvals, fee schedules, payout runs)",
    "Orders integration: a customer order with lines from three vendors creates one payment and three vendor sub-orders; fulfilment per vendor; returns and refunds allocate per vendor; disputes (PAP-423 mapping) route to the vendor with platform oversight",
  ],
  'scope_out': ['Vendor self-signup marketing pages', 'Cross-tenant marketplaces (tenants selling to other tenants)', 'Escrow beyond Stripe holds'],
  'spec': [
    'Money split is computed server-side per line from the fee schedule and recorded before charging; Stripe transfer amounts must equal the recorded split (assertion) or the order fails closed',
    'Vendors see only their own lines, customers and payouts; RLS predicates scope by `vendor_id` through the audience attribute (PAP-227)',
    'Payout statements are immutable PDFs with a hash; a correction is a new statement',
    'Fee changes apply to new orders only; the schedule is versioned',
  ],
  'provides': "`MarketplacePort` default adapter, `vendor` audience surfaces, tables, split and payout logic, statements, posting rules, `vendor.payout.created`, `listing.*` events",
  'consumes': "orders, Connect onboarding and transfers (PAP-181), payout and statement pattern (PAP-408), audiences (PAP-55), portal shell pattern (PAP-62), attribute predicates (PAP-227), approvals, print kit (PAP-235), dispute mapping (PAP-423)",
  'consumed_by': "packs (marketplace pack in v0.3 wave 4), growth (vendor CRM), platform-ops (Connect health per vendor)",
  'dod': ['Demo: three vendors onboarded in test mode, a mixed order splits and pays, each vendor fulfils its part in the vendor portal, one refund allocates correctly, a payout statement is generated and postings reconcile to Stripe balance transactions'],
  'tests': {
    'Unit': 'split math with fees, taxes and discounts; statement determinism; fee schedule versioning',
    'Integration': 'transfer amount assertion; vendor RLS scoping; dispute routing; payout webhook mapping',
  },
  'demo': "Buy from three vendors in one cart, show the split preview, pay in test mode, fulfil one line as a vendor, refund another, and generate the monthly statements.",
  'edge': ['Vendor Connect account restricted after the sale: transfers fail; funds stay on the platform balance with a task for staff; the vendor portal shows the requirement', 'Discount code spanning vendors: allocated proportionally and the platform absorbs rounding'],
  'deps': f"`r4/{K}/orders-fulfilment` (hard), PAP-181 (hard), PAP-408 (soft: pattern), PAP-55, PAP-62, PAP-227 (hard), PAP-423 (soft).",
  'builder': 'Ledger', 'reviewer': 'Sentinel (Security Auditor)',
 },
 {
  'key': f'r4/{K}/vertical-packs-wave2', 'title': 'Author vertical packs wave 2 on the pack format: salon and spa, gym and studio, law firm, real estate brokerage, with pages, views, pipelines, services, chart of accounts, terminology, workflows, documents and sample data',
  'type': 'Build', 'tier': 'sonnet', 'effort': 'medium', 'size': 'L', 'priority': 4, 'surfaces': ['Staff', 'Customer'], 'milestone': MS[2], 'deferred': True,
  'blockedBy': ['PAP-426', 'PAP-427', 'PAP-126', f'r4/{K}/catalog-inventory', f'r4/{K}/projects-time-billing'], 'blocks': [f'r4/{K}/pack-conformance-tests'],
  'goal': "Extend the five packs (PAP-427) with four more on the same `pack.yaml` format (PAP-426): salon and spa (services, resources, booking page, retail shelf, loyalty), gym and studio (memberships, classes, check-in), law firm (matters as projects, time billing, documents and e-sign, restricted trust accounts), real estate brokerage (listings as a dataset with map view, showings as bookings, commission splits, transaction checklists), each with terminology (PAP-126), workflows, documents and sample data.",
  'scope_in': [
    "`packs/salon`, `packs/gym`, `packs/law`, `packs/real-estate`: `pack.yaml` with `tables[]`, `views[]`, `pipelines[]`, `services[]`, `resources[]`, `chartOfAccounts[]`, `pages[]`, `navigation`, `docs[]`, `workflows[]`, `documents[]`, `characters[]` (assistant starters), `sampleData/*.jsonl`, `roles[]`, `entitlements`, `modules` (enable engagement, commerce, workflows as needed)",
    "Terminology entries in `industries.yaml` (PAP-126) for each (client/guest/member/matter/listing) and default compliance profile hints (law: retention 7 years, trust account restrictions)",
    "Pack docs: a one-page \"what you get\" per pack rendered in the template gallery (PAP-428) with screenshots from the conformance run; Scout's Template Packager sub-character authors, Ledger reviews chart of accounts",
  ],
  'scope_out': ['New platform features: a pack may only compose existing objects; gaps found while authoring are filed as issues on the owning project', 'Localised legal templates (documents are marked `review required`)'],
  'spec': [
    'Every pack applies to a blank tenant with `--dry-run` producing an empty diff on re-apply (idempotent) and lints clean (PAP-426 lint minimums plus terminology coverage ≥ 90 percent of renamed concepts)',
    'Sample data is flagged `demo: true` and removable in one action; no real names or addresses',
    'Each pack declares its module dependencies; applying to a tenant without a module offers to enable it (PAP-266) or skips that content with a report',
    'Home dashboard per pack composed from PAP-173 blocks; at least one starter workflow and one document template per pack',
  ],
  'provides': "four pack directories, terminology entries, gallery cards, starter characters, sample data",
  'consumes': "pack format and applier (PAP-426), the five packs (PAP-427), template gallery (PAP-428), business profile (PAP-126), module toggles (PAP-266), commerce, engagement, workflows and assistant objects (soft: content skipped when a module is absent)",
  'consumed_by': f"`r4/{K}/pack-conformance-tests`, PAP-428 gallery, PAP-208 migration agent (recommends packs), PAP-429 golden path (new canned ideas)",
  'dod': ['Four packs apply, lint and re-apply idempotently in CI; gallery shows them with screenshots; a law demo tenant runs a matter from intake form to signed engagement letter to invoice using only pack content'],
  'tests': {
    'Static': 'pack lint; terminology coverage; schema validation of every file',
    'Integration': 'apply to blank tenant, dry-run diff empty on second apply, remove sample data leaves structure',
  },
  'demo': "Apply the salon pack to a blank tenant from the gallery, open the booking page, sell a product at the shelf POS, and show the terminology (guest, treatment) across navigation and notifications.",
  'edge': ['Pack applied to a tenant that already has a `customers` table: conflict strategy `merge` maps fields by name and reports what it could not map (PAP-426 strategies)'],
  'deps': "PAP-426, PAP-427 (hard), PAP-126, PAP-428 (hard), commerce catalog and projects (soft), engagement booking and memberships (soft), workflows (soft).",
  'builder': 'Scout', 'reviewer': 'Ledger (Bookkeeper)', 'tenant_data': False, 'module_edge': False,
 },
 {
  'key': f'r4/{K}/vertical-packs-wave3', 'title': 'Author vertical packs wave 3: ecommerce, nonprofit, school, church, construction, property management, trades and field service',
  'type': 'Build', 'tier': 'sonnet', 'effort': 'medium', 'size': 'L', 'priority': 4, 'surfaces': ['Staff', 'Customer'], 'milestone': MS[2], 'deferred': True,
  'blockedBy': [f'r4/{K}/vertical-packs-wave2', f'r4/{K}/orders-fulfilment', f'r4/{K}/assets-work-orders', 'PAP-426'], 'blocks': [f'r4/{K}/pack-conformance-tests'],
  'goal': "Finish the list in the brief with seven packs on the same format: ecommerce (catalog, orders, fulfilment, returns, subscriptions, reviews), nonprofit (donors as contacts, donations as documents with fund accounting in the chart of accounts, pledges, volunteers as shifts, grant projects), school (students and guardians as audiences, classes as group services, enrolment forms, tuition invoicing, attendance), church (members, giving, groups, events with bookings, volunteer scheduling), construction (jobs as projects, estimates via documents and e-sign, subcontractor bills, change orders, daily logs as forms, progress billing), property management (properties and units as assets, leases as customer subscriptions, maintenance work orders, tenant portal, owner statements), trades and field service (work orders, estimates, parts, technician mobile flow, service agreements).",
  'scope_in': [
    "Seven pack directories with the full `pack.yaml` content set as in wave 2; terminology and compliance hints (school: student privacy profile; nonprofit: fund and restricted gift accounts; property: security deposit liability accounts)",
    "Audience definitions per pack (`student`, `guardian`, `donor`, `member`, `tenant-resident`, `owner`, `subcontractor`) composed from PAP-55 segments with portal navigation per audience",
    "Gallery cards, starter workflows (enrolment, donation acknowledgement, lease renewal, change order approval), starter documents (receipt letters, lease, estimate), starter assistant characters",
  ],
  'scope_out': ['Regulatory filings (990s, 1099s, tax receipts formats beyond a template marked review required)', 'Payment rails beyond Stripe (ACH is Stripe ACH)'],
  'spec': [
    'Same idempotency, lint and coverage rules as wave 2; property management leases must produce correct deposit liability postings in the conformance run',
    'Fund accounting for nonprofits and churches uses account dimensions on `fin_account` (PAP-392) rather than parallel charts; the pack documents the convention',
    'School packs default to the strictest privacy profile for the `student` audience and never expose guardian contact data to other guardians (attribute policy in the pack roles)',
  ],
  'provides': "seven pack directories, audiences and terminology entries, gallery cards, starter content",
  'consumes': "wave 2 conventions, pack format (PAP-426), orders and assets (commerce), subscriptions (leases), engagement bookings and memberships, workflows and documents, audiences (PAP-55)",
  'consumed_by': f"`r4/{K}/pack-conformance-tests`, PAP-428, PAP-208, PAP-429",
  'dod': ['Seven packs apply, lint and re-apply idempotently; gallery shows eleven new packs in total; a property management demo runs lease → rent invoice → maintenance work order → owner statement from pack content'],
  'tests': {
    'Static': 'pack lint and coverage; audience policy tests generated from pack roles (PAP-64 pattern)',
    'Integration': 'apply each pack to a blank tenant in CI shards; posting traces for donation, tuition, rent and progress billing fixtures',
  },
  'demo': "Apply the property management pack, add a unit and a resident, start the lease subscription in test mode, log a maintenance request from the resident portal, complete it as a technician, and generate the owner statement.",
  'edge': ['Tenant applies two packs (church plus school): shared objects merge by name; navigation shows both audiences; the report lists overlaps'],
  'deps': f"`r4/{K}/vertical-packs-wave2` (hard: conventions), `r4/{K}/orders-fulfilment`, `r4/{K}/assets-work-orders`, `r4/{K}/customer-subscriptions` (soft: content skipped when absent), PAP-426 (hard).",
  'builder': 'Scout', 'reviewer': 'Ledger (Bookkeeper)', 'tenant_data': False, 'module_edge': False,
 },
 {
  'key': f'r4/{K}/pack-conformance-tests', 'title': 'Build pack conformance in CI: every pack applies to a blank tenant, home dashboard screenshots at seven widths, terminology and audience policy checks, posting traces, and golden-path acceptance extension',
  'type': 'Review', 'tier': 'sonnet', 'effort': 'medium', 'size': 'M', 'priority': 4, 'surfaces': ['Developer'], 'milestone': MS[2], 'deferred': True,
  'blockedBy': [f'r4/{K}/vertical-packs-wave2', f'r4/{K}/vertical-packs-wave3', 'PAP-429', 'PAP-246', 'PAP-239'], 'blocks': [],
  'goal': "Keep sixteen packs honest as the platform changes under them: a nightly and per-PR job that applies every pack to a blank tenant, runs the pack's own smoke flow, captures the home dashboard and three key pages at the seven-width matrix (PAP-246), checks terminology coverage and generated audience policy tests, verifies posting traces against golden ledgers, and extends the PAP-429 golden path with one canned idea per pack family.",
  'scope_in': [
    "`ops/ci/packs.yml`: sharded job (four shards) applying packs from `packs/*` to per-shard blank tenants on the compose stack; `pack.yaml` gains `smoke: [{ flow, expect }]` for a scripted Playwright flow per pack",
    "Artefacts: `packs.json` in the PAP-239 shape (per pack: apply time, lint, coverage, smoke pass, screenshots, posting diff); contact sheet of home dashboards; failures open a Linear comment on the pack's owning issue",
    "Golden path extension: PAP-429 gains ideas \"a salon in Leeds\", \"a plumbing company\", \"a small private school\" mapped to packs and asserting the pack content is present in the generated app",
  ],
  'scope_out': ['Pack authoring', 'Visual review beyond the existing vision agent (PAP-84 inspects the contact sheet)'],
  'spec': [
    'A pack that fails to apply blocks merges touching `packs/` or any contract the pack depends on (compat matrix PAP-440 lists them)',
    'Posting golden files per pack are versioned with the pack; a change requires a Ledger review comment',
    'Runtime budget: full run under 25 minutes across shards; per-PR runs only the affected packs (dependency map)',
  ],
  'provides': "packs CI job, `packs.json` artefact, `smoke` schema, golden posting files, golden-path ideas",
  'consumes': "packs wave 2 and 3 and PAP-427, golden path acceptance (PAP-429), Playwright matrix (PAP-246), gate artefacts (PAP-239), compat matrix (PAP-440), vision inspection (PAP-84)",
  'consumed_by': "quality release digest (pack health section, PAP-89), PAP-428 gallery (screenshots), platform-ops compliance evidence",
  'dod': ['Nightly run green for all sixteen packs on staging; per-PR affected-pack selection proven; a deliberately broken pack fails exactly its shard; golden path asserts three new ideas'],
  'tests': ['Meta: break one pack field mapping and confirm the failure names the pack and file.', 'Determinism: two runs produce identical `packs.json` except timings.'],
  'demo': "Open the nightly contact sheet of sixteen home dashboards at 375 and 1920, then show a PR that changed the scheduling contract running only the four packs that depend on it.",
  'edge': ['Compose stack flake: the job retries a shard once and quarantines flaky smoke flows through PAP-90 rather than blocking every pack'],
  'deps': f"`r4/{K}/vertical-packs-wave2` and `r4/{K}/vertical-packs-wave3` (hard), PAP-429, PAP-246, PAP-239 (hard), PAP-440, PAP-84, PAP-90 (soft).",
  'builder': 'Sentinel', 'reviewer': 'Scout', 'tenant_data': False, 'module_edge': False,
 },
]

TRIO = trio({
    'key': K, 'lead': 'Ledger', 'owner': 'Ledger', 'kind': 'runtime', 'swapRisk': 'medium', 'impl': 'packages/commerce, apps/web/src/commerce, packs/*',
    'milestones': MS, 'impl_keys': [f'r4/{K}/catalog-inventory', f'r4/{K}/orders-fulfilment', f'r4/{K}/projects-time-billing', f'r4/{K}/hr-core'],
    'publish_blockedBy': [f'r4/{K}/domain-model'],
    'ports': ['`CatalogPort` (`products`, `variants`, `priceLists`, `resolvePrice`) with `Product`, `Variant`, `PriceList`', '`InventoryPort` (`stock`, `move`, `reserve`, `release`, `count`) with `StockLocation`, `StockMovement`', '`OrderPort` (`create`, `pay`, `fulfil`, `return`, `refund`) with `Order`, `OrderLine`, `Fulfilment`, `Return`; `ShippingLabelPort`', '`PosPort` (`session`, `sale`, `tender`, `closeShift`) and `TerminalPort`', '`PurchasingPort` (`po`, `receive`, `bill`, `match`, `schedulePayment`)', '`ProjectsPort` (`projects`, `timeEntries`, `timer`, `invoiceFromTime`) and `HrPort` (`directory`, `timeOff`, `shifts`, `timesheets`, `toPayroll`)', '`AssetsPort` (`assets`, `schedules`, `workOrders`), `SubscriptionsPort`, `MarketplacePort` (`vendors`, `listings`, `split`, `payouts`)', '`PackPort` (`apply`, `lint`, `conformance`) with the `pack.yaml` extensions (`services`, `resources`, `workflows`, `documents`, `characters`, `smoke`)', 'slots `portal.orders`, `record.panel.tabs.stock`, `dashboard.blocks.commerce`, `pos.tender.methods`, `shell.header.actions` (timer)'],
    'events': ['product.updated', 'stock.moved', 'stock.low', 'order.created', 'order.paid', 'order.fulfilled', 'order.returned', 'order.refunded', 'pos.sale.completed', 'pos.shift.closed', 'po.issued', 'po.received', 'bill.approved', 'bill.paid', 'time.entry.logged', 'timesheet.approved', 'timeoff.approved', 'shift.published', 'workorder.created', 'workorder.completed', 'subscription.customer.activated', 'subscription.customer.cancelled', 'vendor.payout.created'],
    'requires': ['`@paperos/contract-business-core` ^0.1 (finance model, ledger, posting rules, documents, Checkout, Connect, Tax, payroll)', '`@paperos/contract-tables` ^0.1 (datasets, views, field types, calendar, Gantt)', '`@paperos/contract-data-layer` ^0.1 (jobs, idempotency, files, audit, recurrence, offline outbox)', '`@paperos/contract-identity` ^0.1 (`Principal`, audiences incl. `vendor`, attribute predicates)', '`@paperos/contract-workflows` ^0.1 (approvals, forms, e-sign; optional)', '`@paperos/contract-engagement` ^0.1 (availability shape, loyalty tenders; optional)', '`@paperos/contract-app-shell` ^0.1 (kiosk mode, native scanner and camera)', '`@paperos/contract-migration` ^0.1 (pack format and applier)'],
    'fixtures': 'a 50-product catalog with 300 variants and 500 movements across two locations, twelve orders across the status machine with posting traces, one POS shift with mixed tenders and an offline replay, a PO-receipt-bill match trio, two projects with forty time entries and a retainer, a two-week schedule with clock events and a payroll export, ten assets with a maintenance schedule and three work orders, two customer subscriptions with webhook fixtures, a three-vendor split order, and sixteen pack manifests',
    'consumers': 'business-core reports (PAP-183), growth (order and subscription activity), engagement (loyalty earn, shifts), assistant (order and stock tools), platform-ops (commerce metrics), migration (gallery and importers)',
})

ISSUES = [TRIO[0]] + ISSUES + TRIO[1:]
